---
title: "R Notebook"
output: html_notebook
---

```{r}
####################### SURGICAL PLANNING V2 ###########################
library(shiny)
library(shinyWidgets)
library(sf)
library(tidyverse)
library(ggplot2)
library(shinyBS)
library(cowplot)
library(magick)
library(ggpattern)
library(glue)
library(rlist)
library(janitor)
library(lubridate)
library(redcapAPI)
library(ggpmisc)
library(rclipboard)
library(nngeo)
library(shinydashboard)
# 
# library(shinyauthr)
# library(sodium)

# rcon <- redcapConnection(url = 'https://redcap.wustl.edu/redcap/api/', token = "58C0BC0A6CA8B8DFB21A054C2F5A3C49")
# rcon <- redcapConnection(url = 'https://redcap.uthscsa.edu/REDCap/api/', token = "2A930AE845C92CBF95467E59ADBA0D20")

source("short_shiny_functions.R", local = TRUE)
source("make_geoms_functions.R", local = TRUE)
source("build_spine_objects_functions.R", local = TRUE)
source("load_coordinates_build_objects.R", local = TRUE)
source("anterior_posterior_operative_note_generator_functions.R", local = TRUE)
source("load_coordinates_build_objects_6_lumbar.R", local = TRUE)
source("no_implants_added_op_note.R", local = TRUE)
source("screw_size_type_inputs.R", local = TRUE)
source("modal_functions.R", local = TRUE)



cpt_unformatted_df <- read_csv(file = "cpt_codes_rvus_unformatted.csv") %>%
  clean_names() %>%
  remove_empty()
  # %>%
  # rename(section = x4)


all_implants_constructed_df %>%
  select(category) %>%
  distinct()
```


```{r}
# all_implants_constructed_df %>%
#   select(level, vertebral_number, approach, side, object) %>%
#   mutate(level)
# cpt_names_wide_df

cpt_names_wide_df <- cpt_unformatted_df %>%
  fill(cpt_code, .direction = "down")%>%
  fill(work_rvus, .direction = "down") %>%
  group_by(cpt_code) %>%
  mutate(count_id = row_number()) %>%
  pivot_wider(names_from = count_id, values_from = descriptor, names_prefix = "col") %>%
  ungroup()

glue_collapse(names(cpt_names_wide_df %>% select(-cpt_code, -work_rvus, -section )), sep = " = ' ', ")

cpt_section_region_procedures_df <- cpt_names_wide_df %>%
  replace_na(list(col1 = ' ', col2 = ' ', col3 = ' ', col4 = ' ', col5 = ' ', col6 = ' ', col7 = ' ', col8 = ' ', col9 = ' ', col10 = ' ', col11 = ' ', col12 = ' ', col13 = ' ', col14 = ' ', col15 = ' ', col16 = ' ')) %>%
  mutate(descriptor = paste(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15, col16)) %>%
  select(cpt_code,section, work_rvus, descriptor) %>%
  mutate(descriptor = str_trim(str_squish(descriptor))) %>%
  mutate(cpt_code = str_squish(cpt_code)) %>%
  mutate(procedure = str_to_lower(descriptor)) %>%
  mutate(procedure = str_remove_all(procedure, "- ")) %>%
  select(-descriptor) %>%
  mutate(spine_region = case_when(
    str_detect(procedure, "each additional| in conjunction") ~ "additional_segment",
    str_detect(procedure, "c1-c2") ~ "C1-C2",
    str_detect(procedure, "odontoid ") ~ "Odontoid",
    str_detect(procedure, "l5-s1 ") ~ "L5-S1",
    str_detect(procedure, "atlant") ~ "Occipito-Cervical",
    str_detect(procedure, "cervical") ~ "Cervical",
    str_detect(procedure, "thoracic") ~ "Thoracic",
    str_detect(procedure, "lumbar") ~ "Lumbar",
    str_detect(procedure, "pelv") ~ "Pelvis",
    str_detect(procedure, "sacral") ~ "Sacral",
    TRUE ~ "unspecified"
  ))%>%
  select(cpt_code, section, spine_region, procedure, work_rvus)

cpt_codes_no_addon_codes_df <- cpt_section_region_procedures_df %>%
  filter(spine_region != "additional_segment")

unique(cpt_codes_no_addon_codes_df$spine_region)

# cpt_codes_no_addon_codes_df

# write_csv(x = cpt_codes_no_addon_codes_df, file = "cpt_codes_no_addon_codes_df.csv")



```


```{r}
cpt_spine_regions_removed_from_procedure_df <- cpt_section_region_procedures_df %>%
  mutate(procedure_no_spine_region = str_remove_all(procedure, ", sacral|, lumbosacral|, lumbar|, thoracolumbar|, thoracic|, cervicothoracic|, cervical")) %>%
  mutate(procedure_no_spine_region = str_remove_all(procedure_no_spine_region, "; sacral|; lumbosacral|; lumbar|; thoracolumbar|; thoracic|; cervicothoracic|; cervical")) %>%
  mutate(procedure_no_spine_region = str_remove_all(procedure_no_spine_region, " sacral| or lumbosacral| lumbar| or thoracolumbar| thoracic| or cervicothoracic| cervical")) %>%
  # select(section, cpt_code, procedure_no_spine_region) %>%
  distinct() 
  # mutate(code_number = row_number()) %>%
  # select(code_number, everything())

cpt_primary_procedures_no_addons_regions_removed_df <- cpt_spine_regions_removed_from_procedure_df %>%
  filter(spine_region != "additional_segment") %>%
  select(cpt_code, section, procedure_no_spine_region) %>%
  distinct()
```


```{r}
cpt_primary_procedures_no_addons_regions_removed_df


primary_procedures_no_addons_regions_removed_no_codes_df <- cpt_primary_procedures_no_addons_regions_removed_df %>%
  select(section, procedure_no_spine_region) %>%
  distinct()

primary_procedures_no_addons_regions_removed_no_codes_df

cpt_section_region_procedures_df %>%
  

write_csv(x = cpt_primary_procedures_no_addons_regions_removed_df, file = "cpt_spine_regions_removed_from_procedure_df.csv", na = "")


write_csv(x = primary_procedures_no_addons_regions_removed_no_codes_df, file = "primary_procedures_no_addons_regions_removed_no_codes_df.csv", na = "")
```
### ADD ON CODES
```{r}
addition_codes_wide_df <- cpt_section_region_procedures_df %>%
  separate(col = procedure, into = c("procedure", "additional_segment_instruction"), sep = "\\(use ") %>%
  separate(col = additional_segment_instruction, into = c("addition_code", "primary_code_to_add_to"), sep = " in conjunction with ") %>%
  mutate(primary_code_to_add_to = str_remove_all(primary_code_to_add_to, "\\)")) %>%
  separate(primary_code_to_add_to, into = c('primary_1', 'primary_2', 'primary_3', 'primary_4', 'primary_5', 'primary_6', 'primary_7', 'primary_8', 'primary_9', 'primary_10', 'primary_11', 'primary_12', 'primary_13', 'primary_14', 'primary_15', 'primary_16', 'primary_17', 'primary_18', 'primary_19', 'primary_20', 'primary_21', 'primary_22', 'primary_23', 'primary_24', 'primary_25', 'primary_26', 'primary_27', 'primary_28', 'primary_29', 'primary_30', 'primary_31', 'primary_32', 'primary_33', 'primary_34', 'primary_35', 'primary_36', 'primary_37', 'primary_38', 'primary_39', 'primary_40'), sep = ", ", extra = "merge") %>%
  filter(!is.na(addition_code)) %>%
  select(cpt_code, addition_code, contains("primary")) %>%
  remove_empty()

addition_codes_long_df <- addition_codes_wide_df %>%
  pivot_longer(cols = contains("primary"), names_to = "code_number", values_to = "code") %>%
  filter(!is.na(code))%>%
  select(-cpt_code)


addon_codes_that_had_ranges_df <- addition_codes_long_df %>%
  filter(str_detect(code, "-")) %>%
  separate(code, into = c("start", "finish"), sep = "-") %>%
  mutate(start = as.double(start), finish = as.double(finish)) %>%
  mutate(code_row = row_number()) %>%
  mutate(code = map(.x = code_row, .f = ~ c(start[.x]:finish[.x]))) %>%
  unnest() %>%
  select(addition_code, code) %>%
  distinct() %>%
  group_by(addition_code) %>%
  mutate(row_count = row_number()) %>%
  ungroup() %>%
  mutate(code_number = paste0("primary_", row_count)) %>%
  select(-row_count) %>%
  mutate(code = as.integer(code))

addon_codes_that_had_and_df <- addition_codes_long_df %>%
  filter(str_detect(code, "or|and")) %>%
  separate(code, into = c("primary_1", "primary_2"), sep = " and ") %>%
  select(addition_code, primary_1, primary_2) %>%
  pivot_longer(cols = contains("primary"), names_to = "code_number", values_to = "code")%>%
  mutate(code = as.integer(code))

addon_codes_that_had_merged_codes_df <- addition_codes_long_df %>%
    filter(str_detect(code, "-", negate = TRUE)) %>%
  filter(str_detect(code, "and|or", negate = TRUE)) %>%
  filter(str_length(code) > 6)%>%
  mutate(primary_1 = substr(code, start = 1, stop = 5))%>%
  mutate(primary_2 = substr(code, start = 6, stop = 10)) %>%
    select(addition_code, primary_1, primary_2) %>%
  pivot_longer(cols = contains("primary"), names_to = "code_number", values_to = "code") %>%
  mutate(code = as.integer(code))

addon_codes_that_had_merged_codes_df


addition_codes_with_primary_assc_long_df <- addition_codes_long_df %>%
  filter(str_detect(code, "-", negate = TRUE)) %>%
  filter(str_detect(code, "and|or", negate = TRUE)) %>%
  filter(str_length(code) < 6) %>%
  mutate(code = as.integer(code)) %>%
  union_all(addon_codes_that_had_ranges_df) %>%
  union_all(addon_codes_that_had_and_df) %>%
  union_all(addon_codes_that_had_merged_codes_df) %>%
  select(addition_code, code) %>%
  distinct() %>%
  mutate(addition_code = as.integer(addition_code)) %>%
  arrange(addition_code) %>%
  group_by(addition_code) %>%
  mutate(code_number_row = row_number()) %>%
  ungroup() %>%
  mutate(code_number = paste0("primary_", code_number_row)) %>%
  select(addition_code, code_number, primary_code = code) %>%
  distinct()
  

addon_codes_that_had_ranges_df

addition_codes_wide_df
  
# write_csv(x = addition_codes_wide_df, file = "add_on_codes_wide_df.csv", na = "") 
```

```{r}
all_implants_constructed_df %>%
  select(approach, category, object) %>%
  distinct()

op_note_object_labels_df <- tibble(object = c("vertebroplasty", "Vertebroplasty")) %>% mutate(category = c("object", "label")) %>%
    union_all(tibble(object = c("vertebral_cement_augmentation", "Vertebral body augmentation")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("laminar_downgoing_hook", "Posterior spinal instrumentation")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("laminar_upgoing_hook", "Posterior spinal instrumentation")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("lateral_mass_screw", "Posterior spinal instrumentation")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("occipital_screw", "Occiput instrumentation")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("pars_screw", "Posterior spinal instrumentation")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("pedicle_hook", "Posterior spinal instrumentation")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("pedicle_screw", "Posterior spinal instrumentation")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("crosslink", "Posterior spinal instrumentation")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("laminar_downgoing_hook", "Posterior spinal instrumentation")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("sublaminar_wire", "Posterior spinal instrumentation")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("tp_hook", "Posterior spinal instrumentation")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("translaminar_screw", "Posterior spinal instrumentation")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("pelvic_screw", "Pelvic instrumentation")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("pelvic_screw_1", "Pelvic instrumentation")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("pelvic_screw_2", "Pelvic instrumentation")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("tether", "Spinous process posterior tethering/wiring")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("costovertebral_approach", "Decompression using a costovertebral approach")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("revision_costovertebral_approach", "Reexploration and revision decompression using a costovertebral approach")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("transpedicular_approach", "Decompression using a transpedicular approach")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("lateral_extracavitary_approach", "Decompression using a modified lateral extracavitary approach")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("corpectomy_extracavitary_tumor", "Partial Corpectomy with decompression using a modified lateral extracavitary approach for tumor")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("laminectomy_for_tumor", "Laminectomy for biopsy and excision of extradural spinal tumor")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("revision_transpedicular_approach", "Reexploration and revision decompression using a transpedicular approach")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("diskectomy", "Decompression with diskectomy and laminotomy")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("sublaminar_decompression", "Decompression with bilateral partial laminectomies, foraminotomies, and medial facetectomies")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("laminectomy", "Decompression with central laminectomy")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("laminotomy",  "Decompression with laminotomy and medial facetectomy")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("revision_diskectomy", "Reexploration and revision decompression with diskectomy and laminotomy")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("revision_sublaminar_decompression", "Reexploration and revision decompression with bilateral partial laminectomies, foraminotomies, and medial facetectomies")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("revision_laminectomy", "Reexploration and revision decompression with central laminectomy")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("revision_laminotomy", "Reexploration and revision decompression with laminotomy and medial facetectomy")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("laminoplasty", "Laminoplasty")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("grade_1", "Inferior facetectomies")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("complete_facetectomy", "Decompression with a complete facetectomy")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("grade_2", "Posterior column osteotomy")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("grade_3", "Pedicle subtraction osteotomy")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("grade_4", "Extended three column osteotomy (vertebral body partial corpectomy)")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("grade_5", "Vertebral column resection")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("costotransversectomy", "Costovertebral approach with costotransversectomy")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("no_implant_interbody_fusion", "Interbody fusion (without interbody implant)")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("llif", "Lateral lumbar interbody fusion and insertion of interbody device")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("plif", "Posterior lumbar interbody fusion and insertion of interbody device")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("tlif", "Transforaminal lumbar interbody fusion and insertion of interbody device")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("intervertebral_cage", "Insertion of intervertebral biomechanical implant")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("structural_allograft", "Application of structural allograft")) %>% mutate(category = c("object", "label"))) %>%
    ## ANTERIOR
    union_all(tibble(object = c("anterior_disc_arthroplasty", "Total disk arthroplasty")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("decompression_diskectomy_fusion", "Anterior diskectomy and fusion with decompression of the central canal and nerve roots")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("diskectomy_fusion", "Anterior diskectomy and fusion")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("diskectomy_fusion_no_interbody_device", "Anterior diskectomy and fusion")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("anterior_interbody_implant", "Insertion of interbody biomechanical implant")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("corpectomy", "Anterior vertebral corpectomy")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("corpectomy_cage", "Anterior insertion of intervertebral biomechanical implant")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("anterior_plate", "Anterior spinal instrumentation (distinct from an interbody implant)")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("anterior_buttress_plate", "Anterior spinal instrumentation (distinct from an interbody implant)")) %>% mutate(category = c("object", "label"))) %>%
    union_all(tibble(object = c("screw_washer", "Anterior spinal instrumentation (distinct from an interbody implant")) %>% mutate(category = c("object", "label"))) %>%
  pivot_wider(names_from = category, values_from = object) %>%
  unnest()


op_note_labels_cpt_templated_df <- op_note_object_labels_df %>%
  mutate(sacral_label = "sacral_cpt", l5_s1_label = "l5_s1_cpt", lumbar_label = "lumbar_cpt", thoracic_label = "thoracic_cpt", cervical_label = "cervical_cpt", odontoid_label = "odontoid_cpt", c1_c2_label = "c1_c2_cpt", unspecified_label = "unspecified_level_cpt", modified_by_dx_label = "modifiy_by_dx_cpt") %>%
  pivot_longer(cols = c(-object, -label), names_to = "labels", values_to = "level") %>%
  mutate(level = str_remove_all(labels, "_label")) %>%
  mutate(cpt_code = " ") %>%
  mutate(cpt_description = " ")

# write_csv(x = op_note_labels_cpt_templated_df, file = "op_note_labels_cpt_templated_df.csv")

```



```{r}
cpt_section_region_procedures_df %>%
  select(section) %>%
  distinct()


cpt_section_region_procedures_df %>%
  filter(section == "Osteotomy") %>%
  filter(spine_region == "additional_segment") %>%
  separate(col = procedure, into = c("procedure", "additional_segment_instruction"), sep = "\\(use ") %>%
  separate(col = additional_segment_instruction, into = c("addition_code", "primary_code_to_add_to"), sep = " in conjunction with ") %>%
  mutate(primary_code_to_add_to = str_remove_all(primary_code_to_add_to, "\\)")) %>%
  separate(primary_code_to_add_to, into = c("primary_1", "primary_2", "primary_3"), sep = ", ", extra = "merge")

cpt_section_region_procedures_df %>%
  filter(str_detect(procedure, "laminectomy for biopsy/excision of"))

```

```{r}
cpt_section_region_procedures_df


```

