---
title: "R Notebook"
output: html_notebook
---

```{r}
library(shiny)
library(shinyWidgets)
library(sf)
library(tidyverse)
library(ggplot2)
library(shinyBS)
library(cowplot)
library(magick)
library(ggpattern)
library(glue)
library(rlist)
library(janitor)
library(lubridate)
library(redcapAPI)
# library(ggpmisc)
# library(rclipboard)
library(nngeo)# 
library(shinydashboard)
source("short_shiny_functions.R", local = TRUE)
source("make_geoms_functions.R", local = TRUE)
source("build_spine_objects_functions.R", local = TRUE)
source("load_coordinates_build_objects.R", local = TRUE)
source("anterior_posterior_operative_note_generator_functions.R", local = TRUE)
source("load_coordinates_build_objects_6_lumbar.R", local = TRUE)
# source("no_implants_added_op_note.R", local = TRUE)
source("screw_size_type_inputs.R", local = TRUE)

```


```{r}
# test_df <- jh_generate_test_screw_df(full_df = all_implants_constructed_df, levels_vector = c("L3", "L4", "L5")) %>%
#   left_join(all_shiny_screw_options_long_df)

possible_objects_long_df <- all_implants_constructed_df %>%
  filter(str_detect(object, "screw")) %>%
  select(level, vertebral_number, side, object) %>%
  mutate(level_side_object = paste(level, side, object,sep = "_")) %>%
  mutate(level_side_object = str_to_lower(level_side_object)) %>%
  mutate(object_diameter_label = paste(level_side_object, "diameter", sep = "_")) %>%
  mutate(object_length_label = paste(level_side_object, "length", sep = "_")) %>%
  arrange(vertebral_number) %>%
  select(level, vertebral_number, object, side, level_side_object)


all_shiny_screw_options_long_df <- possible_objects_long_df %>%
  mutate(diameter_label = paste(level_side_object, "_diameter", sep = "")) %>%
  mutate(length_label = paste(level_side_object, "_length", sep = "")) %>%
  mutate(diameter_input = map(.x = diameter_label, .f = ~numericInput(inputId = .x, label = NULL, value = 0))) %>%
  mutate(length_input = map(.x = length_label, .f = ~numericInput(inputId = .x, label = NULL, value = 0)))

left_input_options_df <- all_shiny_screw_options_long_df %>%
  filter(side == "left") %>%
  select(level, left_diameter_label = diameter_label, left_diameter_input = diameter_input, left_length_label = length_label, left_length_input = length_input) %>%
  mutate(count = row_number())


right_input_options_df <- all_shiny_screw_options_long_df %>%
  filter(side == "right") %>%
  select(level, right_diameter_label = diameter_label, right_diameter_input = diameter_input, right_length_label = length_label, right_length_input = length_input)%>%
  mutate(count = row_number())


wide_options <- left_input_options_df %>%
  left_join(right_input_options_df) %>%
  mutate(left_object = str_remove_all(left_diameter_label, "_diameter")) %>%
  mutate(right_object = str_remove_all(right_diameter_label, "_diameter")) %>%
  mutate(object = str_remove_all(right_object, "right_"))%>%
  mutate(object_label = str_to_title(str_replace_all(object, "_", " ")))

wide_options

left_input_diameter_list <- wide_options$left_diameter_input
names(left_input_diameter_list) <- wide_options$left_diameter_label

left_input_length_list <- wide_options$left_length_input
names(left_input_length_list) <- wide_options$left_length_label

right_input_diameter_list <- wide_options$right_diameter_input
names(right_input_diameter_list) <- wide_options$right_diameter_label

right_input_length_list <- wide_options$right_length_input
names(right_input_length_list) <- wide_options$right_length_label


```


```{r}
possible_objects_long_df <- all_implants_constructed_df %>%
  filter(str_detect(object, "screw")) %>%
  select(level, vertebral_number, side, object) %>%
  mutate(level_side_object = paste(level, side, object,sep = "_")) %>%
  mutate(level_side_object = str_to_lower(level_side_object)) %>%
  mutate(object_diameter_label = paste(level_side_object, "diameter", sep = "_")) %>%
  mutate(object_length_label = paste(level_side_object, "length", sep = "_")) %>%
  arrange(vertebral_number) %>%
  select(level, vertebral_number, object, side, level_side_object)



```


```{r}
possible_objects_long_df

```


```{r}
possible_objects_long_df <- all_implants_constructed_df %>%
  filter(str_detect(object, "screw")) %>%
  select(level, vertebral_number, side, object) %>%
  mutate(level_side_object = paste(level, side, object,sep = "_")) %>%
  mutate(level_side_object = str_to_lower(level_side_object)) %>%
  mutate(object_diameter_label = paste(level_side_object, "diameter", sep = "_")) %>%
  mutate(object_length_label = paste(level_side_object, "length", sep = "_")) %>%
  arrange(vertebral_number) %>%
  select(level, vertebral_number, object, side, level_side_object)

  all_shiny_screw_options_long_df <- possible_objects_long_df %>%
    mutate(diameter_label = paste(level_side_object, "_diameter", sep = "")) %>%
    mutate(length_label = paste(level_side_object, "_length", sep = "")) %>%
    mutate(diameter_input = map(.x = diameter_label, .f = ~numericInput(inputId = .x, label = NULL, value = 0,
                                                                        width = '50%'))) %>%
    mutate(length_input = map(.x = length_label, .f = ~numericInput(inputId = .x, label = NULL, value = 0,
                                                                        width = '50%')))
  
  left_input_options_df <- all_shiny_screw_options_long_df %>%
    filter(side == "left") %>%
    select(level, left_diameter_label = diameter_label, left_diameter_input = diameter_input, left_length_label = length_label, left_length_input = length_input) %>%
    mutate(count = row_number())
  
  
  right_input_options_df <- all_shiny_screw_options_long_df %>%
    filter(side == "right") %>%
    select(level, right_diameter_label = diameter_label, right_diameter_input = diameter_input, right_length_label = length_label, right_length_input = length_input)%>%
    mutate(count = row_number())
  
  
  all_possible_screw_input_labels_wide_df <- left_input_options_df %>%
    left_join(right_input_options_df) %>%
    mutate(left_object = str_remove_all(left_diameter_label, "_diameter")) %>%
    mutate(right_object = str_remove_all(right_diameter_label, "_diameter")) %>%
    mutate(object = str_remove_all(right_object, "right_"))%>%
    mutate(object_label = str_to_title(str_replace_all(object, "_", " ")))
  
  left_input_diameter_list <- all_possible_screw_input_labels_wide_df$left_diameter_input
  names(left_input_diameter_list) <- all_possible_screw_input_labels_wide_df$left_diameter_label
  
  left_input_length_list <- all_possible_screw_input_labels_wide_df$left_length_input
  names(left_input_length_list) <- all_possible_screw_input_labels_wide_df$left_length_label
  
  right_input_diameter_list <- all_possible_screw_input_labels_wide_df$right_diameter_input
  names(right_input_diameter_list) <- all_possible_screw_input_labels_wide_df$right_diameter_label
  
  right_input_length_list <- all_possible_screw_input_labels_wide_df$right_length_input
  names(right_input_length_list) <- all_possible_screw_input_labels_wide_df$right_length_label
  
  
  
  table_row_list <- pmap(.l = 
                           list(
                             ..1 = all_possible_screw_input_labels_wide_df$level, 
                             ..2 = all_possible_screw_input_labels_wide_df$object_label,
                             ..3 = left_input_diameter_list,
                             ..4 = left_input_length_list,
                             ..5 = right_input_diameter_list,
                             ..6 = right_input_length_list
                           ), 
                         .f = ~ tags$table(
                           tags$tr(width = "100%", 
                                        tags$td(width = "40%", div(style = "font-size:12px; font-weight:bold; text-align:center; padding-bottom:10px", paste(..2))),
                                        tags$td(width = "15%",
                                                ..3
                                        ),
                                        tags$td(width = "15%", 
                                                # div(
                                          ..4
                                        # )
                                        ),
                                        tags$td(width = "15%", 
                                                # div( 
                                          ..5
                                        # )
                                        ),
                                        tags$td(width = "15%",
                                                # div(
                                          ..6
                                        # )
                                        )
                         )
                         )
  )
  
  names(table_row_list) <- all_possible_screw_input_labels_wide_df$object
  


```


```{r}
tags$table(
  map(.x = test_vector_objects, .f = ~ table_row_list[[.x]])
  
)

# condition = 'input.control && input.control.indexOf("a") > -1'

screw_size_input_tables_list$c2_pedicle_screw$children

all_possible_screw_input_labels_wide_df

names(table_row_list)
```
```{r}
all_implants_constructed_df %>%
            select(level, vertebral_number, object, side) %>%
            distinct() %>%
            filter(str_detect(object, "screw")) %>%
            arrange(vertebral_number) %>%
            mutate(level_object = paste(level, object, sep = "_"))

all_possible_screw_input_labels_wide_df %>%
  select(level, contains("label")) %>%
  mutate(left_diameter_value = input[[left_diameter_label]]) %>%
  mutate(left_length_value = input[[left_length_label]]) %>%
  mutate(right_diameter_value = input[[right_diameter_label]]) %>%
  mutate(right_length_value = input[[right_length_label]])

all_shiny_screw_options_long_df

screw_type_input_tables_list$c2_pedicle_screw

screw_size_input_tables_list$c2_pars_screw

rm(screw_type_input_tables_list, screw_size_input_tables_list)

radioGroupButtons( #"option2",  
                            inputId = "test", 
                            label = NULL, 
                            choices = c("M", "U", "P", "Red", "Offset"),
                            selected = "P",
                            checkIcon = list(yes = icon("wrench")),
                            size = "xs", 
                            direction = "horizontal",
                            justified = TRUE,
                            width = "95%"
                          )

# awesomeRadio(inputId = "test", label = NULL, choices = c("M", "U", "P", "Red", "Offst"), selected = "P", inline = TRUE, stat)
```

################################################################################
right_{str_to_lower(level)}_screw_diameter

```{r}
all_shiny_screw_options_long_df


all_possible_screw_input_labels_wide_df

    left_selected_df <- tibble(left_object = c("left_c2_pars_screw", "left_c3_pedicle_screw", "left_c4_pedicle_screw")) %>%
      left_join(all_possible_screw_input_labels_wide_df) %>%
      select(-contains("right"))
    
   right_selected_df <- tibble(right_object = c("right_c4_pedicle_screw", "right_c5_pedicle_screw", "right_c6_pedicle_screw")) %>%
      left_join(all_possible_screw_input_labels_wide_df) %>%
      select(-contains("left"))
   
   left_selected_df %>% 
     full_join(right_selected_df)
   
all_possible_screw_input_labels_wide_df$left_diameter_input[[1]]

all_possible_screw_input_labels_wide_df$level[[3]]

shiny_column_screw_input_df <- all_possible_screw_input_labels_wide_df %>%
  select(level, object, object_label, contains("input")) %>%
  mutate(bilateral_input = pmap(list(
                                  ..1 = object_label,
                                  ..2 = left_diameter_input, 
                                ..3 = left_length_input, 
                                ..4 = right_diameter_input,
                                ..5 = right_length_input), 
         .f = ~ fluidRow(
           column(4, 
                             ..1), 
                      column(2, 
                             ..2), 
                      column(2, 
                             ..3), 
                      column(2, 
                             ..4), 
                      column(2, 
                             ..5)))
  )
```


```{r}
screw_shiny_input_options_long_df <- all_implants_constructed_df %>%
  select(level, vertebral_number, side, object) %>%
  filter(str_detect(object, "screw")) %>%
  filter(side == "left" | side == "right") %>%
  mutate(level_side_object = str_to_lower(paste(side, level, object, sep = "_"))) %>%
  mutate(diameter_input = map(.x = level_side_object, .f = ~numericInput(inputId = paste0(.x, "_diameter"),
                                                                      label = NULL, 
                                                                      value = 0,
                                                                      width = '75%'))) %>%
    mutate(length_input = map(.x = level_side_object, .f = ~numericInput(inputId = paste0(.x, "_length"),
                                                                      label = NULL, 
                                                                      value = 0,
                                                                      width = '75%'))) %>%
  mutate(type_input = map(.x = level_side_object,
                          .f = ~ radioGroupButtons( #"option2",  
                            inputId = .x,
                            label = NULL, 
                            choices = c("M", "U", "P", "Red", "Offset"),
                            selected = "P",
                            checkIcon = list(yes = icon("wrench")),
                            size = "xs", direction = "horizontal",
                            justified = TRUE,
                            width = "95%"
                          )
  )) %>%
  arrange(vertebral_number) %>%
  mutate(level_object = str_to_title(string = str_replace_all(paste(level, object, sep = " "), "_", " ")))


left_screw_shiny_input_options_long_df <- screw_shiny_input_options_long_df %>%
  filter(side == "left") %>%
  select(level, level_object, left_object = level_side_object, left_diameter_input = diameter_input, left_length_input = length_input, left_type_input = type_input)


right_screw_shiny_input_options_long_df <- screw_shiny_input_options_long_df %>%
  filter(side == "right") %>%
  select(level, level_object, right_object = level_side_object, right_diameter_input = diameter_input, right_length_input = length_input, right_type_input = type_input)


screw_shiny_inputs_wide_df <- left_screw_shiny_input_options_long_df %>%
  full_join(right_screw_shiny_input_options_long_df) %>%
  mutate(implant_id = row_number()) %>%
  select(implant_id, everything()) %>%
  mutate(bilateral_input = pmap(list(
                                  ..1 = level_object,
                                  ..2 = left_diameter_input, 
                                ..3 = left_length_input, 
                                ..4 = right_diameter_input,
                                ..5 = right_length_input), 
         .f = ~ fluidRow(
           column(4, 
                             ..1), 
                      column(2, 
                             ..2), 
                      column(2, 
                             ..3), 
                      column(2, 
                             ..4), 
                      column(2, 
                             ..5)))
  ) %>% 
    mutate(left_only_input = pmap(list(
                                  ..1 = level_object,
                                  ..2 = left_diameter_input, 
                                ..3 = left_length_input),
         .f = ~ fluidRow(
           column(4, 
                             ..1), 
                      column(2, 
                             ..2), 
                      column(2, 
                             ..3), 
                      column(2, 
                             " "), 
                      column(2, 
                             " ")))
  ) %>% 
    mutate(right_only_input = pmap(list(
                                  ..1 = level_object,
                                  ..2 = right_diameter_input, 
                                ..3 = right_length_input), 
         .f = ~ fluidRow(
           column(4, 
                             ..1), 
                      column(2, 
                             ..2), 
                      column(2, 
                             ..3), 
                      column(2, 
                             " "), 
                      column(2, 
                             " ")))
  )

screw_shiny_inputs_wide_df

test_vector <- c("left_c3_pedicle_screw", "left_c4_pedicle_screw", "left_c5_pedicle_screw", "right_c3_pedicle_screw")

selected_levels_df <- screw_shiny_inputs_wide_df %>%
  select(implant_id, left_object, right_object) %>%
  pivot_longer(cols = -implant_id, names_to = "side", values_to = "side_level_object") %>%
  right_join(tibble(side_level_object = test_vector)) %>%
  pivot_wider(names_from = side, values_from = side_level_object) %>%
  replace_na(list(left_object = "xxx", right_object = "xxx")) %>%
  mutate(laterality_inputs = case_when(
    left_object != "xxx" & right_object != "xxx" ~ "bilateral", 
    left_object == "xxx" & right_object != "xxx" ~ "right",
    left_object != "xxx" & right_object == "xxx" ~ "left_only"))


screw_shiny_inputs_wide_df %>%
  left_join(selected_levels_df) %>%
  replace_na(list(laterality_inputs = "none"))



```


```{r}
ui <- shinyUI(basicPage(
  
  box(width = 12,
      column(6, 
             pickerInput(inputId = "left_screw_options", 
                         label = "Select Left Screws", 
                         choices = screw_shiny_inputs_wide_df$left_object,
                         multiple = TRUE)
      ),
      column(6, 
             pickerInput(inputId = "right_screw_options", 
                         label = "Select Right Screws", 
                         choices = screw_shiny_inputs_wide_df$right_object,
                         multiple = TRUE)
             ),
      box(width = 12,  
          switchInput(inputId = "test", label = "Switch", value = FALSE),
             conditionalPanel(condition = "input.test == true",
                              pickerInput(inputId = "screw_options_for_verification", selected = NULL, multiple = TRUE, 
                                          choices = append(screw_shiny_inputs_wide_df$left_object, screw_shiny_inputs_wide_df$right_object)), 
                              pickerInput(inputId = "screw_levels", 
                                          choices = screw_shiny_inputs_wide_df$level_object, 
                                          multiple = TRUE)
             )
          ),
      hr(),
      box(width = 12, 
          title = "Screw Size Inputs",
          map(.x = c(1:nrow(screw_shiny_inputs_wide_df)),
              .f = ~ fluidRow(
                column(12, 
                       conditionalPanel(condition = glue("input.screw_levels.indexOf('{screw_shiny_inputs_wide_df$level_object[.x]}') >-1"),
                        screw_shiny_inputs_wide_df$bilateral_input[.x]                 
                       )
                )
              )
          )
      )
  ), 
  hr(),
  box(width = 12, 
      tableOutput(outputId = "screw_details_redcap_df_sidetab")
      )

))

server <- function(input, output, session) {
  
  observeEvent(list(input$left_screw_options, input$right_screw_options), {
    updatePickerInput(session = session, 
                      inputId = "screw_options_for_verification", 
                      selected = append(input$left_screw_options, input$right_screw_options))
  })
  
  screws_selected_df_reactive <- reactive({
    
    if(length(input$left_screw_options)>0){
      left_selected_df <- tibble(left_object = input$left_screw_options) %>%
        left_join(screw_shiny_inputs_wide_df) %>%
        select(-contains("right"))
    }else{
      left_selected_df <- screw_shiny_inputs_wide_df %>% filter(level == "x") %>%
        select(-contains("right"))
    }
    
    if(length(input$right_screw_options)>0){
      right_selected_df <- tibble(right_object = input$right_screw_options) %>%
        left_join(screw_shiny_inputs_wide_df) %>%
        select(-contains("left"))
    }else{
      right_selected_df <- screw_shiny_inputs_wide_df %>% filter(level == "x") %>%
        select(-contains("left"))
    }
    
    left_selected_df %>% 
      full_join(right_selected_df)
    
  })
  
  observeEvent(list(input$left_screw_options, input$right_screw_options), {
    updatePickerInput(session = session, 
                      inputId = "screw_levels", 
                      choices = screws_selected_df_reactive()$level_object,
                      selected = screws_selected_df_reactive()$level_object)
  })
  
  
  output$screw_details_redcap_df_sidetab <- renderTable({
    
    screws_selected_df_reactive() %>%
      select(level, object_label, left_object, right_object) 
    
    # all_shiny_screw_options_long_df %>%
    #   select(level, side, diameter_label, length_label) %>%
    #   mutate(diameter_value = map(.x = diameter_label, .f = ~ input[[.x]])) %>%
    #   mutate(length_value = map(.x = length_label, .f = ~ input[[.x]]))  %>%
    #   unnest() %>%
    #   mutate(diameter_value = as.double(diameter_value), length_value = as.double(length_value)) %>%
    #   filter(diameter_value > 0)
    
  })
  
  
  
}

# rm(ui, server)

shinyApp(ui = ui, server = server)
```


```{r}


# ui <- shinyUI(basicPage(
#   
#   box(width = 12,
#       column(3, 
#              pickerInput(inputId = "screw_options", 
#                          label = "Select Screws", 
#                          choices = names(screw_size_input_tables_list),
#                          multiple = TRUE), 
#              br(), 
#              switchInput(inputId = "test", label = "Switch", value = FALSE),
#              conditionalPanel(condition = "input.test == true",
#                               pickerInput(inputId = "screw_options_for_verification", selected = NULL, multiple = TRUE, 
#                                           choices = names(screw_size_input_tables_list))
#              )
#          ),
#       column(9, 
#              map(.x = c(1:length(screw_size_input_tables_list)),
#               .f = ~ conditionalPanel(
#                 condition = glue("input.screw_options_for_verification.indexOf('{names(screw_size_input_tables_list[.x])}') > -1"),
#                                       screw_size_input_tables_list[[.x]],
#                 screw_type_input_tables_list[[.x]]
#                                       )
#              )
#       )
#   ), 
#   box(width = 12, 
#       tableOutput(outputId = "screw_details_redcap_df_sidetab")
#       )
# 
# ))
# 
# server <- function(input, output, session) {
#   
#   observeEvent(input$screw_options, {
#     updatePickerInput(session = session, 
#                       inputId = "screw_options_for_verification", 
#                       selected = input$screw_options)
#   })
#   
#     observeEvent(input$screw_options, {
#       
#       
#     updatePickerInput(session = session, 
#                       inputId = "screw_options_for_verification", 
#                       selected = input$screw_options)
#   })
#   
#       output$screw_details_redcap_df_sidetab <- renderTable({
#         
#         all_shiny_screw_options_long_df %>%
#           select(level, side, diameter_label, length_label) %>%
#           mutate(diameter_value = map(.x = diameter_label, .f = ~ input[[.x]])) %>%
#           mutate(length_value = map(.x = length_label, .f = ~ input[[.x]]))  %>%
#           unnest() %>%
#           mutate(diameter_value = as.double(diameter_value), length_value = as.double(length_value)) %>%
#           filter(diameter_value > 0)
#         
#     })
#       
# 
#   
# }
# 
# 
# shinyApp(ui = ui, server = server)

```

```{r}
rm(ui, server)
```


```{r}
all_possible_screw_input_labels_wide_df %>%
            select(level, contains("label"))  %>%
  pivot_longer(cols = c("left_diameter_label", "right_diameter_label"), names_to = )

append(all_possible_screw_input_labels_wide_df$left_diameter_label, all_possible_screw_input_labels_wide_df$right_diameter_label)


all_shiny_screw_options_long_df %>%
            select(level, side, diameter_label, length_label) %>%
  filter(level %in% c("L3", "L4"), str_detect(diameter_label, "pedicle")) %>%
  mutate(screw_diameter = 5, screw_length = 5) %>%
  mutate(screw_size = paste0(screw_diameter, "x", screw_length, "mm")) %>%
  select(screw_level = level, screw_side = side, screw_diameter, screw_length, screw_size)
```


