---
title: "R Notebook"
output: html_notebook
---

```{r}
library(shiny)
library(sf)
library(tidyverse)
library(ggplot2)
library(shinyWidgets)
library(shinyBS)
# library(colourpicker)
# library(kableExtra)
library(cowplot)
# library(ggpubr)
library(magick)
library(ggpattern)
library(glue)
library(rlist)
library(janitor)
library(lubridate)
library(redcapAPI)
# library(ggpmisc)
# library(rclipboard)
library(shinyCopy2clipboard)

source("hook_function.R", local = TRUE)
source("screw_function.R", local = TRUE)
source("osteotomies_decompressions_functions.R", local = TRUE)
source("load_coordinates.R", local = TRUE)

# remotes::install_github("deepanshu88/shinyCopy2clipboard")


```


```{r}

test_surgery_df <- all_implants_constructed_df %>%
  filter(level == "C5-C6" | level == "C4-C5"| level == "C3-C4") %>%
  filter(object == "diskectomy_fusion" |  object == "anterior_plate")

test_surgery_df


all_implants_constructed_df %>%
  filter(approach == "anterior") %>%
  tabyl(object)

all_implants_constructed_df %>%
  filter(level == "C5-C6" | level == "C4-C5"| level == "C3-C4")


test_surgery_df

map(.x =  test_surgery_df$level, ~ paste("Anterior Cervical Diskectomy and Fusion at ", .x))

glue_collapse(map(.x =  test_surgery_df$level, ~ paste("Anterior Cervical Diskectomy and Fusion at ", .x)), sep = "\n")

p_list <- list()


p_list <- append(p_list, values = map(.x =  test_surgery_df$level, ~ paste("Anterior Cervical Diskectomy and Fusion at ", .x)))


p_list
test_surgery_df

test_list <- full_anterior_op_note_generator_function(all_objects_to_add_df = test_surgery_df, anterior_approach_laterality = "left", acdf_interbody_height = 8, interbody_device = "Peek Cage")


numbers_test <- map2(.x = c(1:length(test_list$procedures_performed_summary_list)), .y = test_list$procedures_performed_summary_list, .f = ~ paste(.x, ". ", .y, sep = ""))


glue_collapse(numbers_test, sep = "\n")

```


```{r}

  test_op_note_df <- test_surgery_df %>%
    select(-object_constructed) %>%
    union_all(fusion_levels_df) %>%
    mutate(object = str_to_lower(object)) %>%
    mutate(object = str_replace_all(object, "_", " ")) %>%
    filter(approach == "anterior") 

test_op_note_df
  


  
  test_levels_df <- test_op_note_df %>%
    filter(vertebral_number == min(vertebral_number) | vertebral_number == max(vertebral_number)) %>%
    mutate(level = if_else(vertebral_number >=25, "S1", level)) %>%
    select(level, vertebral_number) %>%
    distinct() %>%
    arrange(vertebral_number)  
  
  test_levels_df
  
  
test_levels_df <- test_levels_df %>%
    mutate(vertebral_number = if_else(str_detect(level, "-"), vertebral_number - 0.5, vertebral_number)) %>%
    union_all(test_levels_df) %>%
    mutate(vertebral_number = round(vertebral_number, 0)) %>%
    select(vertebral_number) %>%
    left_join(levels_numbered_df) %>%
    select(level, vertebral_number) %>%
    distinct()
  
test_levels_df

levels_numbered_df

test_range_vector <- test_levels_df %>%
    filter(vertebral_number == min(vertebral_number) | vertebral_number == max(vertebral_number)) %>%
    select(level) %>%
    as_vector()

test_range_vector[[2]]

```

```{r}
acdf_statement_function <- function(level, interbody_height = 8, interbody_device = "cage"){
  initial_level_statement <- glue("We then began the anterior cervical diskectomy and fusion procedure at the {level} level.")
  
  acdf_procedure_statement <- paste("The anterior disk space was smoothed and any osteophyte resected using a combination of a ronguer and burr. Using a combination of knife, currette, pituitary ronguer, and Kerrison rongeurs, the disc was excised and the superior and inferior endplates were lightly decorticated, taking care not to disrupt the cortical endplate. The posterior longitudinal ligament was excised and adequate central decompression was confirmed. Foraminotomies were performed bilaterally to fully decompress the left and the right exiting nerve roots. Once the decompression was complete and the endplates were prepared, a trial was inserted to size the disk space.",
                                    glue("The {interbody_height}mm trial fit appropriately. We then inserted a {interbody_height}mm height {interbody_device} into the disk space."),sep = " "
                                    )    
  
  paste(initial_level_statement, acdf_procedure_statement, sep = " ")
}

acdf_statement_function(level = "C5-C6")


test_surgery_df %>%
  filter(object == "anterior_plate") %>%
  arrange(vertebral_number)

test_surgery_df

anterior_plate_lower_numbers_df <- test_surgery_df %>%
  filter(object == "anterior_plate") %>%
  arrange(vertebral_number) %>%
  mutate(vertebral_number = vertebral_number - 0.5) %>%
  select(vertebral_number) 

anterior_plate_lower_numbers_df

anterior_plate_test_df <- anterior_plate_lower_numbers_df %>%
  filter(vertebral_number == max(vertebral_number)) %>%
  mutate(vertebral_number = vertebral_number + 1) %>%
  union_all(anterior_plate_lower_numbers_df) %>%
  arrange(vertebral_number) %>%
  left_join(levels_numbered_df)

anterior_plate_test_df

glue_collapse(anterior_plate_test_df$level, sep = ", ", last = " and ")
  
  test_surgery_df %>%
  filter(object == "anterior_plate") %>%
  arrange(vertebral_number) %>%
  mutate(vertebral_number = vertebral_number - 0.5) %>%
  select(vertebral_number) 

anterior_plate_test_df

anterior_plate_test_df$level[[2]]

glue_collapse()

```

```{r}


anterior_test_list <- full_anterior_op_note_generator_function(all_objects_to_add_df = test_surgery_df, anterior_approach_laterality = "left", deep_drains = 1)

procedures_performed_df <- tibble(procedure = anterior_test_list$procedures_performed_summary_list) %>%
                unnest() %>%
                mutate(procedure = paste(row_number(), procedure, sep = ". "))

procedures_performed_df

anterior_test_list$procedure_details_list

glue_collapse(anterior_test_list$procedure_details_list, sep = "\n")

glue_collapse(x = anterior_test_list$procedure_details_list, sep = '\n\n')


test <- all_implants_constructed_df %>%
  filter(level == "L1-L2" | level == "L2-L3") %>%
  filter(object == "diskectomy_fusion") %>%
  select(level, vertebral_number, approach, category, object, side) 


test2 <- test  %>%
  union_all(test %>%
  mutate(object = "anterior_interbody_implant") ) %>%
  arrange(vertebral_number) %>%
  mutate(implant_statement = "test_implant_statement")
            
```




```{r}




test_list <- op_note_anterior_function(all_objects_to_add_df = test2,
                                                                anterior_approach_laterality = "left",
                                                                acdf_interbody_height = "9mm", 
                                                                interbody_device = "cage",
                                                                microscope_statement = "none", 
                                                                # antibiotics = input$preop_antibiotics, 
                                                                # additional_procedures_vector = input$additional_procedures, 
                                                                # bmp = if_else(input$bmp_number == 0, 0, (as.double(input$bmp_number)*as.double(input$bmp_size))), 
                                                                # bone_graft_vector = input$bone_graft,
                                                                # morselized_allograft = input$allograft_amount,
                                                                # morselized_autograft_separate = 0,
                                                                # structural_allograft_location = input$structural_allograft_location,
                                                                # additional_procedural_details = c(), 
                                                                deep_drains = 1,
                                                                superficial_drains = 1,
                                                                # end_procedure_details =,
                                                                closure = c("Dermabond"),
                                                                dressing = c("Prineo"))


test_list$procedure_details_paragraph
```

