---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}

source("labels_screws_functions.R", local = TRUE)
```


```{r}
screw_screwhead_long_df

screw_start_df

string <- glue(cat(screw_start_df$side))

map(screw_start_df$side, .f = cat)[1]

paste(screw_start_df$side, sep="", collapse="") 


min(st_boundary(c3_lm_screw_screwhead$left_screw_sf))

summary(c3_lm_screw_screwhead$left_screw_sf)

st_nearest_points(screw_list)

left_screwhead_point_1 <- c4_lm_screw_screwhead$left_screw_rotated[[1]][2,]
left_screwhead_point_2 <- c4_lm_screw_screwhead$left_screw_rotated[[1]][3,]

mean(mat1[1], mat2[1])

c(mean(left_screwhead_point_1[1], left_screwhead_point_2[1]), mean(left_screwhead_point_1[2], left_screwhead_point_2[2]))

screwhead_list

left_rod_df <- screw_screwhead_long_df %>%
                  select(implant, side, screw_heads) %>%
                pivot_wider(names_from = side, values_from = "screw_heads")

left_rod_df$left[[1]]


left_rod_df <- do.call(rbind, left_rod_df$left)

left_rod_df %>%
  as_tibble() %>%
  arrange(V2) %>%
  as.matrix()

rbind(left_rod_df$left)

transpose(left_rod_df$left)

st_buffer(st_linestring(left_rod_df), dist = 0.001)

sum(str_count(screw_screwhead_long_df$side, pattern = "left"))
 
```
### ILIAC 
```{r}
screw_function <- function(screw_start_x_offset, screw_start_y, screw_type, angle, screw_length_modifier = 1, screw_width_modifier = 1, y_scale = 1){
  
  rot = function(a) matrix(c(cos(a), sin(a), -sin(a), cos(a)), 2, 2)
  
  screw_length <- 0.02*screw_length_modifier
  
  screw_width <- 0.01*screw_width_modifier
  
  #### LEFT SCREW ####
  
  left_screw_start <- c(0.5 - screw_start_x_offset, screw_start_y)
  
  right_screw_start <- c(0.5 + screw_start_x_offset, screw_start_y)
  
  screw_width <- case_when(
    screw_type == "pedicle" ~ screw_width/2,
    screw_type == "lateral mass" ~ screw_width/4,
    screw_type == "pars" ~ screw_width/4,
    screw_type == "translaminar" ~ screw_width/2,
    screw_type == "iliac" | screw_type == "s2ai" ~ screw_width/2 
  )
  
  screw_length <- case_when(
    screw_type == "pedicle" ~ screw_length,
    screw_type == "lateral mass" ~ screw_length/2,
    screw_type == "pars" ~ screw_length/2,
    screw_type == "translaminar" ~ screw_length,
    screw_type == "iliac" | screw_type == "s2ai" ~ screw_length 
  )
  
  left_point_1 <- st_point(c(left_screw_start[1], left_screw_start[2]))
  left_point_2 <- st_point(c(left_point_1[1] - screw_length, left_point_1[2] + screw_width))
  left_point_3 <- st_point(c(left_point_1[1] - screw_length, left_point_1[2] - screw_width))
  
  left_screw <- st_polygon(list(rbind(left_point_1, left_point_2, left_point_3, left_point_1)))
  
  left_screw_rotated <- (left_screw - left_point_1)*rot(angle*-1*pi/180) + left_point_1
  
  if(screw_type == "iliac" | screw_type == "s2ai"){
    left_screw_rotated <- left_screw_rotated - c(screw_length, +0.01)
  }
  
  left_screw_sf <- st_buffer(x = left_screw_rotated, dist = 0.001, endCapStyle = "SQUARE")
  
  left_screw_sf <- st_buffer(x = left_screw_sf, dist = 0.001, endCapStyle = "ROUND")
  
  
  left_screwhead_point_1 <- left_screw_rotated[[1]][2,]
  left_screwhead_point_2 <- left_screw_rotated[[1]][3,]
  
  left_screw_head <- c(mean(left_screwhead_point_1[1], left_screwhead_point_2[1]), mean(left_screwhead_point_1[2], left_screwhead_point_2[2]))
  
  
  #### RIGHT SCREW ####
  
  right_point_1 <- st_point(c(right_screw_start[1], right_screw_start[2]))
  right_point_2 <- st_point(c(right_point_1[1] + screw_length, right_point_1[2] - screw_width))
  right_point_3 <- st_point(c(right_point_1[1] + screw_length, right_point_1[2] + screw_width))
  
  
  right_screw <- st_polygon(list(rbind(right_point_1, right_point_2, right_point_3, right_point_1)))
  
  
  right_screw_rotated <- (right_screw - right_point_1)*rot(angle*pi/180) + right_point_1
  
  if(screw_type == "iliac" | screw_type == "s2ai"){
    right_screw_rotated <- right_screw_rotated + c(screw_length, -0.01)
  }
  
  right_screw_sf <- st_buffer(x = right_screw_rotated, dist = 0.001, endCapStyle = "SQUARE")
  
  right_screw_sf <- st_buffer(x = right_screw_sf, dist = 0.001, endCapStyle = "ROUND")
  
  right_screwhead_point_1 <- right_screw_rotated[[1]][2,]
  right_screwhead_point_2 <- right_screw_rotated[[1]][3,]
  
  right_screw_head <- c(mean(right_screwhead_point_1[1], right_screwhead_point_2[1]), mean(right_screwhead_point_1[2], right_screwhead_point_2[2]))
  
  
  
  return(list(left_screw_sf = left_screw_sf, 
              left_screw_head = left_screw_head,
              right_screw_sf = right_screw_sf,
              right_screw_head = right_screw_head))
  
}

screw_screwhead_long_df %>%
  group_by(side) %>%
  mutate(vertebral_number = row_number()) %>%
  ungroup()
```

```{r}
iliac_screw_screwhead <- screw_function(screw_start_x_offset = iliac_x_offset, screw_start_y = iliac_y, screw_type = "iliac",screw_length_modifier = 3, angle = -150)

s2ai_screw_screwhead <- screw_function(screw_start_x_offset = s2ai_x_offset, screw_start_y = s2ai_y, screw_type = "s2ai", screw_length_modifier = 3, angle = -155)

left <- screw_screwhead_long_df %>%
                select(implant, side, screw_heads, vertebral_number) %>%
                arrange(vertebral_number) %>%
                pivot_wider(names_from = side, values_from = "screw_heads") %>%
  select(implant, left)


left
left_rod_df <- do.call(rbind, left$left)

right <- screw_screwhead_long_df %>%
                select(implant, side, screw_heads, vertebral_number) %>%
                arrange(vertebral_number) %>%
                pivot_wider(names_from = side, values_from = "screw_heads") %>%
  select(implant, right)

right
right_rod_df <- do.call(rbind, right$right)

left_rod_df

right_rod_df
```
```{r}
translaminar_screw_screwhead_long_df %>%
  separate(col = implant, into = c("side", "level"), sep = "_", remove = FALSE) %>%
  left_join(vertebral_number_df)

translaminar_screw_screwhead_long_df

screw_screwhead_long_df %>%
  union_all(translaminar_screw_screwhead_long_df) 
  distinct()
  
  tibble("labels" = levels_vector) %>%
  mutate(y = label_y_vector, 
         left = 0.5 - label_x_offset,
         right = 0.5 + label_x_offset)
  pivot_longer(cols = c(left, right), names_to = "side", values_to = "x") %>%
  select(labels, side, x, y)

```



### RODS

```{r}

all_screws <- st_multipolygon((screw_screwhead_long_df$screws))


right_rods_long_df <- implants_list$implants_df %>%
  right_join(screw_screwhead_long_df) %>%
  select(implant, side, screw_heads)



if(str_detect(string = right_rods_long_df$side, pattern = "right")){
  right_rods_wide_df <- right_rods_long_df %>%
    pivot_wider(names_from = side, values_from = "screw_heads")
  
  right_rod_df <- do.call(rbind, right_rods_wide_df$right)
  
  right_rod_sf <- st_buffer(st_linestring(right_rod_df), dist = 0.001)
}else{
  right_rod_sf <- NULL
}


l2_hook <- hook_function(hook_start_x_offset = 0.02, hook_start_y = l2_y)

l2_hooks <- list(l2_hook$left_upgoing_hook, l2_hook$left_downgoing_hook_sf, l2_hook$right_downgoing_hook_sf)

l2_upgoing_hooks_collection <-st_geometrycollection(list(l2_hook$left_upgoing_hook, l2_hook$right_downgoing_hook))
l2_downgoing_hooks_collection <-st_geometrycollection(list(l2_hook$left_downgoing_hook, l2_hook$right_downgoing_hook))

ggdraw() +
      draw_image(spine_png, scale = 1, y = 0, valign = 0, x = 0, width = 1) +
      draw_text(text = labels_df$labels, x = labels_df$x_left, y = labels_df$y, size = 12, fontface = "bold") +
      draw_text(text = labels_df$labels, x = labels_df$x_right, y = labels_df$y, size = 12, fontface = "bold") +
      geom_point(aes(x = 0.5 - iliac_x_offset, y = iliac_y), size = 4) + 
  geom_point(aes(x = 0.5 - s2ai_x_offset, y = s2ai_y), size = 4) + 
  geom_sf(data = l2_upgoing_hooks_collection) +
  ggpattern::geom_sf_pattern(data = s2ai_screw_screwhead$left_screw_sf, pattern = "stripe",  pattern_fill = "red",alpha = 0.8, pattern_colour = "blue", pattern_density = 0.01, pattern_spacing = 0.003, angle = 70) +
  ggpattern::geom_sf_pattern(data = s2ai_screw_screwhead$right_screw_sf, pattern = "stripe",  pattern_fill = "red",alpha = 0.8, pattern_colour = "blue", pattern_density = 0.01, pattern_spacing = 0.003, angle = 70) +
  theme_minimal_grid()  +
  ylim(0, 0.5)

```



```{r}

# names(hook_list_df$hooks) <- hook_list_df$levels

hook_list_df <- labels_df %>%
  select(labels, y) %>%
  mutate(level = str_to_lower(labels)) %>%
  filter(level != "occiput", level != "iliac", level != "s2ai") %>%
  mutate(hooks = map(.x = y, .f = ~ hook_function(hook_start_x_offset = 0.01, hook_start_y = .))) %>%
  mutate(left_upgoing_laminar_hook = map(.x =  hooks, .f = ~ pluck(.x = ., "left_upgoing_laminar_hook"))) %>%
  mutate(left_upgoing_pedicle_hook = map(.x =  hooks, .f = ~ pluck(.x = ., "left_upgoing_pedicle_hook"))) %>%
  mutate(left_downgoing_laminar_hook = map(.x =  hooks, .f = ~ pluck(.x = ., "left_downgoing_laminar_hook"))) %>%
  mutate(right_upgoing_laminar_hook = map(.x =  hooks, .f = ~ pluck(.x = ., "right_upgoing_laminar_hook"))) %>%
  mutate(right_upgoing_pedicle_hook = map(.x =  hooks, .f = ~ pluck(.x = ., "right_upgoing_pedicle_hook"))) %>%
  mutate(right_downgoing_laminar_hook = map(.x =  hooks, .f = ~ pluck(.x = ., "right_downgoing_laminar_hook"))) %>%
  pivot_longer(cols = c(-labels, -y, -level, -hooks), names_to = "implant_type", values_to = "hook")%>%
  select(level, implant_type, hook) %>%
  separate(col = implant_type, into = c("side", "direction_hook", "hook_type", "implant_type")) %>%
  mutate(implant = paste(side, level, direction_hook, hook_type, implant_type, sep = "_")) %>%
  select(level, implant, hook) %>%
  left_join(vertebral_number_df)
  

# c(left_upgoing_hook, left_downgoing_hook, right_upgoing_hook, right_downgoing_hook)

upgoing_laminar_hooks <- hook_list_df %>%
  filter(str_detect(implant, pattern = "upgoing_laminar"))

upgoing_pedicle_hooks <- hook_list_df %>%
  filter(str_detect(implant, pattern = "upgoing_pedicle"))

downgoing_laminar_hooks <- hook_list_df %>%
  filter(str_detect(implant, pattern = "downgoing_laminar"))



upgoing_hooks_collection <-st_geometrycollection(upgoing_laminar_hooks$hook)

pedicle_hooks_collection <-st_geometrycollection(upgoing_pedicle_hooks$hook)

downgoing_hooks_collection <-st_geometrycollection(downgoing_laminar_hooks$hook)

ggdraw() +
      draw_image(spine_png, scale = 1, y = 0, valign = 0, x = 0, width = 1) +
      draw_text(text = labels_df$labels, x = labels_df$x_left, y = labels_df$y, size = 12, fontface = "bold") +
      draw_text(text = labels_df$labels, x = labels_df$x_right, y = labels_df$y, size = 12, fontface = "bold") +
      geom_point(aes(x = 0.5 - iliac_x_offset, y = iliac_y), size = 4) + 
  geom_point(aes(x = 0.5 - s2ai_x_offset, y = s2ai_y), size = 4) + 
  geom_sf(data = pedicle_hooks_collection) +
  ggpattern::geom_sf_pattern(data = s2ai_screw_screwhead$left_screw_sf, pattern = "stripe",  pattern_fill = "red",alpha = 0.8, pattern_colour = "blue", pattern_density = 0.01, pattern_spacing = 0.003, angle = 70) +
  ggpattern::geom_sf_pattern(data = s2ai_screw_screwhead$right_screw_sf, pattern = "stripe",  pattern_fill = "red",alpha = 0.8, pattern_colour = "blue", pattern_density = 0.01, pattern_spacing = 0.003, angle = 70) +
  theme_minimal_grid() 


```


### GET PEDICLE Y values
```{r}

xy_lines <- tibble(x_left = 0.45, x_right = 0.55, y = seq(from = 0, to = 1, by = 0.01))

xy_lines

ggdraw() +
      draw_image(spine_png, scale = 1, y = 0, valign = 0, x = 0, width = 1) +
      draw_text(text = labels_df$labels, x = labels_df$x_left, y = labels_df$y, size = 12, fontface = "bold") +
      draw_text(text = labels_df$labels, x = labels_df$x_right, y = labels_df$y, size = 12, fontface = "bold") +
      geom_point(aes(x = 0.5 - iliac_x_offset, y = iliac_y), size = 4) + 
  geom_linerange(data = xy_lines, aes(xmin = x_left, xmax = x_right, y = y, color = y)) +
  draw_text(text = xy_lines$y, x = xy_lines$x_left - 0.05, y = xy_lines$y, size = 7) +
  # geom_text(data = xy_lines,  aes())
  geom_sf(data = pedicle_hooks_collection) +
  ggpattern::geom_sf_pattern(data = s2ai_screw_screwhead$left_screw_sf, pattern = "stripe",  pattern_fill = "red",alpha = 0.8, pattern_colour = "blue", pattern_density = 0.01, pattern_spacing = 0.003, angle = 70) +
  ggpattern::geom_sf_pattern(data = s2ai_screw_screwhead$right_screw_sf, pattern = "stripe",  pattern_fill = "red",alpha = 0.8, pattern_colour = "blue", pattern_density = 0.01, pattern_spacing = 0.003, angle = 70) +
  theme_minimal_grid() +
  ylim(0, 0.5)
  
  
```

```{r}
occiput_pedicle_y <- .917
c1_pedicle_y <- .89
c2_pedicle_y <- .865
c3_pedicle_y <- .848
c4_pedicle_y <- .831
c5_pedicle_y <- .814
c6_pedicle_y <- .797
c7_pedicle_y <- .78
t1_pedicle_y <- .755
t2_pedicle_y <- .73
t3_pedicle_y <- .705
t4_pedicle_y <- .68
t5_pedicle_y <- .65
t6_pedicle_y <- .62
t7_pedicle_y <- .59
t8_pedicle_y <- .56
t9_pedicle_y <- .525
t10_pedicle_y <- .49
t11_pedicle_y <- .455
t12_pedicle_y <- .42
l1_pedicle_y <- .38
l2_pedicle_y <- .35
l3_pedicle_y <- .31
l4_pedicle_y <- .27
l5_pedicle_y <- .235
s1_pedicle_y <- .20
iliac_pedicle_y <- .18
s2ai_pedicle_y <- .15

x <- seq(from = 0.4, to = 0.6, by = 0.001)

y <- seq(from = 0.1, to = 0.9, by = 0.001)

xy_grid <- expand.grid(x, y) %>%
  as_tibble() %>%
  rename(x = Var1, y = Var2) %>%
  mutate(side = if_else(x < 0.5, "left", "right"))

xy_grid

```

## read in coordinates csv's
```{r}
inferior_lamina_raw_coordinates_df <- read_csv("coordinates_inferior_lamina.csv")

superior_lamina_raw_coordinates_df <- read_csv("coordinates_superior_lamina.csv")

start_point_coordinates_df_left <- superior_lamina_raw_coordinates_df %>%
  union_all(inferior_lamina_raw_coordinates_df)

start_point_coordinates_df <- start_point_coordinates_df_left %>%
  mutate(x_right = 0.5 + (0.5-x)) %>%
  mutate(x = x_right) %>%
  select(-x_right) %>%
  mutate(side = "right") %>%
  union_all(start_point_coordinates_df_left)



```

```{r}

hook_list_df <- start_point_coordinates_df %>%
  mutate(laminar_hooks_list = case_when(
    coordinate_type == "superior_lamina" ~ map(.x = y, .f = ~ hook_downgoing_function(hook_start_x_offset = 0.005, hook_edge_y = .)),
    coordinate_type == "inferior_lamina" ~ map(.x = y, .f = ~ hook_function_2(hook_start_x_offset = 0.005, hook_edge_y = .))
    )) %>%
   mutate(hook_implant = case_when(
    coordinate_type == "superior_lamina" & side == "left" ~ map(.x =  laminar_hooks_list, .f = ~ pluck(.x = ., "left_downgoing_laminar_hook")),
    coordinate_type == "inferior_lamina" & side == "left" ~ map(.x = laminar_hooks_list, .f = ~ pluck(.x = ., "left_upgoing_laminar_hook")),
    coordinate_type == "superior_lamina" & side == "right" ~ map(.x =  laminar_hooks_list, .f = ~ pluck(.x = ., "right_downgoing_laminar_hook")),
    coordinate_type == "inferior_lamina" & side == "right" ~ map(.x = laminar_hooks_list, .f = ~ pluck(.x = ., "right_upgoing_laminar_hook"))
   )) %>%
  mutate(hook_implant_type = case_when(
    coordinate_type == "superior_lamina" & side == "left" ~ paste(side, level, "downgoing_laminar_hook", sep = "_"), 
    coordinate_type == "inferior_lamina" & side == "left" ~ paste(side, level, "upgoing_laminar_hook", sep = "_"), 
    coordinate_type == "superior_lamina" & side == "right" ~ paste(side, level, "downgoing_laminar_hook", sep = "_"), 
    coordinate_type == "inferior_lamina" & side == "right" ~ paste(side, level, "upgoing_laminar_hook", sep = "_")
   )) 


hook_starts_df <- start_point_coordinates_df %>%
  mutate(x_offset = 0.03) %>%
  select(level,x_offset, y)%>%
  distinct()

hook_starts_df

superior_lamina_raw_coordinates_df %>%
  select(level, y) %>%
  distinct() %>%
    mutate(x_offset = 0.03) %>%
  select(level,x_offset, y) 

tp_hooks_list_df <- superior_lamina_raw_coordinates_df %>%
  select(level, y) %>%
  distinct() %>%
    mutate(x_offset = case_when(
      str_starts(level, pattern = "t") ~ 0.03,
      level == "l5" ~ 0.04, 
      level == "l4" ~ 0.038, 
      level == "l3" ~ 0.036,
      level == "l2" ~ 0.034,
      level == "l1" ~ 0.032
    )) %>%
  select(level,x_offset, y)  %>% 
  filter(str_detect(string = level, pattern = "l") | str_detect(string = level, pattern = "t")) %>%
  mutate(tp_hooks_list = map2(.x = x_offset, .y = y, .f = ~ hook_tp_function(hook_start_x_offset = .x, hook_edge_y = .y))) %>%
  mutate(left = map(.x =  tp_hooks_list, .f = ~ pluck(.x = ., "left_tp_hook"))) %>%
  mutate(right = map(.x =  tp_hooks_list, .f = ~ pluck(.x = ., "right_tp_hook"))) %>%
  pivot_longer(cols = c(left, right), names_to = "side", values_to = "implant") %>%
  mutate(implant_type = paste(side, level, "tp_hook", sep = "_")) %>%
  select(level, side, implant_type, implant)


tp_hook_heads_list_df <- superior_lamina_raw_coordinates_df %>%
  select(level, y) %>%
  distinct() %>%
    mutate(x_offset = case_when(
      str_starts(level, pattern = "t") ~ 0.03,
      level == "l5" ~ 0.04, 
      level == "l4" ~ 0.038, 
      level == "l3" ~ 0.036,
      level == "l2" ~ 0.034,
      level == "l1" ~ 0.032
    )) %>%
  select(level,x_offset, y)  %>% 
  filter(str_detect(string = level, pattern = "l") | str_detect(string = level, pattern = "t")) %>%
  mutate(tp_hooks_list = map2(.x = x_offset, .y = y, .f = ~ hook_tp_function(hook_start_x_offset = .x, hook_edge_y = .y))) %>%
  mutate(left = map(.x =  tp_hooks_list, .f = ~ pluck(.x = ., "left_tp_hook_head"))) %>%
  mutate(right = map(.x =  tp_hooks_list, .f = ~ pluck(.x = ., "right_tp_hook_head"))) %>%
  pivot_longer(cols = c(left, right), names_to = "side", values_to = "hook_head") %>%
  mutate(implant_type = paste(side, level, "tp_hook", sep = "_")) %>%
  select(level, side, implant_type, hook_head)

tp_hooks_df <- tp_hooks_list_df %>%
  left_join(tp_hook_heads_list_df)

```



```{r}

upgoing_laminar_hooks <- hook_list_df %>%
  filter(str_detect(hook_implant_type, pattern = "upgoing_laminar"))

downgoing_laminar_hooks <- hook_list_df %>%
  filter(str_detect(hook_implant_type, pattern = "downgoing_laminar"))

upgoing_hooks_collection <-st_geometrycollection(upgoing_laminar_hooks$hook_implant)

downgoing_hooks_collection <-st_geometrycollection(downgoing_laminar_hooks$hook_implant)

tp_hooks_collection <-st_geometrycollection(tp_hooks_list_df$implant)

ggdraw() +
      draw_image(spine_png, scale = 1, y = 0, valign = 0, x = 0, width = 1) +
      draw_text(text = labels_df$labels, x = labels_df$x_left, y = labels_df$y, size = 12, fontface = "bold") +
      draw_text(text = labels_df$labels, x = labels_df$x_right, y = labels_df$y, size = 12, fontface = "bold") +
      geom_point(aes(x = 0.5 - iliac_x_offset, y = iliac_y), size = 4) + 
  geom_point(aes(x = 0.5 - s2ai_x_offset, y = s2ai_y), size = 4) + 
  # geom_sf(data = upgoing_hooks_collection, alpha = 0.5) +
  geom_sf(data = tp_hooks_collection, alpha = 0.5) +
  ggpattern::geom_sf_pattern(data = s2ai_screw_screwhead$left_screw_sf, pattern = "stripe",  pattern_fill = "red",alpha = 0.8, pattern_colour = "blue", pattern_density = 0.01, pattern_spacing = 0.003, angle = 70) +
  ggpattern::geom_sf_pattern(data = s2ai_screw_screwhead$right_screw_sf, pattern = "stripe",  pattern_fill = "red",alpha = 0.8, pattern_colour = "blue", pattern_density = 0.01, pattern_spacing = 0.003, angle = 70) +
  theme_minimal_grid() 


```


```{r}

inferior_lamina_raw_coordinates_df <- read_csv("coordinates_inferior_lamina.csv")


# upgoing_hooks_starts_df <- inferior_lamina_raw_coordinates_df %>%
#   mutate(x_offset = 0.02) %>%
#   select(level, x_offset, y) 

hook_list_df <- upgoing_hooks_starts_df %>%
  mutate(hooks = map(.x = y, .f = ~ hook_function_2(hook_start_x_offset = 0.005, hook_edge_y = .))) %>%
  mutate(left_upgoing_laminar_hook = map(.x =  hooks, .f = ~ pluck(.x = ., "left_upgoing_laminar_hook"))) %>%
  # mutate(left_upgoing_pedicle_hook = map(.x =  hooks, .f = ~ pluck(.x = ., "left_upgoing_pedicle_hook"))) %>%
  # mutate(left_downgoing_laminar_hook = map(.x =  hooks, .f = ~ pluck(.x = ., "left_downgoing_laminar_hook"))) %>%
  mutate(right_upgoing_laminar_hook = map(.x =  hooks, .f = ~ pluck(.x = ., "right_upgoing_laminar_hook"))) %>% 
  # mutate(right_upgoing_pedicle_hook = map(.x =  hooks, .f = ~ pluck(.x = ., "right_upgoing_pedicle_hook"))) %>%
  # mutate(right_downgoing_laminar_hook = map(.x =  hooks, .f = ~ pluck(.x = ., "right_downgoing_laminar_hook"))) %>%
  pivot_longer(cols = c(-x_offset, -y, -level, -hooks), names_to = "implant_type", values_to = "hook")%>%
  select(level, implant_type, hook) %>%
  separate(col = implant_type, into = c("side", "direction_hook", "hook_type", "implant_type")) %>%
  mutate(implant = paste(side, level, direction_hook, hook_type, implant_type, sep = "_")) %>%
  select(level, implant, hook) %>%
  left_join(vertebral_number_df)

upgoing_laminar_hooks <- hook_list_df %>%
  filter(str_detect(implant, pattern = "upgoing_laminar"))

upgoing_hooks_collection <-st_geometrycollection(upgoing_laminar_hooks$hook)


ggdraw() +
      draw_image(spine_png, scale = 1, y = 0, valign = 0, x = 0, width = 1) +
      draw_text(text = labels_df$labels, x = labels_df$x_left, y = labels_df$y, size = 12, fontface = "bold") +
      draw_text(text = labels_df$labels, x = labels_df$x_right, y = labels_df$y, size = 12, fontface = "bold") +
      geom_point(aes(x = 0.5 - iliac_x_offset, y = iliac_y), size = 4) + 
  geom_point(aes(x = 0.5 - s2ai_x_offset, y = s2ai_y), size = 4) + 
  geom_sf(data = upgoing_hooks_collection, alpha = 0.5) +
  ggpattern::geom_sf_pattern(data = s2ai_screw_screwhead$left_screw_sf, pattern = "stripe",  pattern_fill = "red",alpha = 0.8, pattern_colour = "blue", pattern_density = 0.01, pattern_spacing = 0.003, angle = 70) +
  ggpattern::geom_sf_pattern(data = s2ai_screw_screwhead$right_screw_sf, pattern = "stripe",  pattern_fill = "red",alpha = 0.8, pattern_colour = "blue", pattern_density = 0.01, pattern_spacing = 0.003, angle = 70) +
  theme_minimal_grid() 

l3_pedicle_y

```

```{r}

# left_screw_start_coordinates_df <- read_csv(file = "coordinates_screw_starts.csv")
# 
# screw_start_coordinates_df <- left_screw_start_coordinates_df %>%
#   mutate(x = 1 - x, side = "right") %>%
#   union_all(left_screw_start_coordinates_df) %>%
#   mutate(x = round(x, 2), y = round(y, 2))

screw_start_coordinates_df

implants_df <- screw_start_coordinates_df %>%
  # filter(level == "l3", side == "left") %>%
  mutate(implant_constructed = pmap(list(..1 = x, 
                                         ..2 = y,
                                         ..3 = angle, 
                                         ..4 = length,
                                         ..5 = width), .f = ~ screw_function_2(screw_type = "pedicle", screw_start_x = ..1, screw_start_y = ..2, angle = ..3, screw_length_modifier = ..4, screw_width_modifier = ..5)))


# implants_df 


implant_starts_df %>%
  tabyl(implant)

```
```{r}
implant_starts_df <- read_csv(file = "coordinates_screw_starts.csv") 

l4_pedicle_screw_df <- implant_starts_df%>%
  filter(implant == "pedicle_screw", side == "left", level == "l4") %>%
  mutate(implant_constructed = pmap(list(..1 = x,
                                         ..2 = y,
                                         ..3 = angle,
                                         ..4 = length,
                                         ..5 = width), .f = ~ screw_function(screw_start_x = ..1, screw_start_y = ..2, angle = ..3, screw_length_modifier = ..4, screw_width_modifier = ..5))) 


l45_pedicle_screw_df <- implant_starts_df%>%
  filter(implant == "pedicle_screw", side == "left", level %in% c("l4", "l5")) %>%
  mutate(implant_constructed = pmap(list(..1 = x,
                                         ..2 = y,
                                         ..3 = angle,
                                         ..4 = length,
                                         ..5 = width), .f = ~ screw_function(screw_start_x = ..1, screw_start_y = ..2, angle = ..3, screw_length_modifier = ..4, screw_width_modifier = ..5))) 

point <- st_point(c(l4_pedicle_screw_df$x[[1]], l4_pedicle_screw_df$y[[1]]))

l45_pedicle_screw_df %>%
  mutate(point_touches = map_lgl(.x = implant_constructed, .f = ~ st_contains(x = .x, y = point, sparse = FALSE))) %>%
  filter(point_touches == FALSE)

point <- st_point(c(l4_pedicle_screw_df$x[[1]], l4_pedicle_screw_df$y[[1]]))

screw_to_test <- l4_pedicle_screw_df$implant_constructed[[1]]

st_contains(x = screw_to_test, y = point, sparse = FALSE)[[1]]

st_contains()

ggplot() + 
  geom_sf(data = screw_to_test) + 
  geom_sf(data = point)

```


```{r}
implant_starts_df <- read_csv(file = "coordinates_screw_starts.csv")

# screws_df <- implant_starts_df %>%
#   filter(implant != "tp_hook") %>%
#   mutate(implant_constructed = pmap(list(..1 = x, 
#                                          ..2 = y,
#                                          ..3 = angle, 
#                                          ..4 = length,
#                                          ..5 = width), .f = ~ screw_function(screw_start_x = ..1, screw_start_y = ..2, angle = ..3, screw_length_modifier = ..4, screw_width_modifier = ..5)))
# 
# hooks_df <- implant_starts_df %>%
#   filter(implant == "tp_hook") %>%
#   remove_empty() %>%
#                   mutate(implant_constructed = pmap(list(..1 = x, 
#                                                        ..2 = y), .f = ~ hook_tp_function(hook_start_x = ..1, hook_edge_y = ..2)))
# 
# 

hooks_upgoing_df <- implant_starts_df %>%
  filter(implant == "laminar_upgoing_hook") %>%
  remove_empty() %>%
                  mutate(implant_constructed = pmap(list(..1 = x, 
                                                       ..2 = y), .f = ~ hook_laminar_function(hook_direction = "upgoing", hook_start_x = ..1, hook_edge_y = ..2)))


hooks_downgoing_df <- implant_starts_df %>%
  filter(implant == "laminar_downgoing_hook") %>%
  remove_empty() %>%
                  mutate(implant_constructed = pmap(list(..1 = x, 
                                                       ..2 = y), .f = ~ hook_laminar_function(hook_direction = "downgoing", hook_start_x = ..1, hook_edge_y = ..2)))


implant_figures <- st_multipolygon(hooks_upgoing_df$implant_constructed)

screws_figures <- st_multipolygon(screws_df$implant_constructed)

ggdraw() +
      draw_image(spine_png, scale = 1, y = 0, valign = 0, x = 0, width = 1) +
      draw_text(text = labels_df$labels, x = 0.45, y = labels_df$y, size = 12, fontface = "bold") +
      draw_text(text = labels_df$labels, x = labels_df$x_right, y = labels_df$y, size = 12, fontface = "bold") +
      geom_point(aes(x = 0.5 - iliac_x_offset, y = iliac_y), size = 4)+
  geom_sf(data = implant_figures) +
  theme_classic() +
  # scale_y_continuous(breaks = seq(from = 0, to = 1, by = 0.05), labels = seq(from = 0, to = 1, by = 0.05)) +
  geom_hline(yintercept = seq(from = 0.2, to = 0.9, by = 0.01), color = "grey", size = 0.01) +
  # geom_vline(xintercept = seq(from = 0.4, to = 0.6, by = 0.01), color = "grey") +
  # ylim(0.7, 1) +
  xlim(0.4, 0.6)



implants_all_df <- implant_starts_df %>%
  left_join(vertebral_number_df) %>%
  mutate(vertebral_number = as.double(vertebral_number)) %>%
  mutate(vertebral_number = if_else(level == "s2ai", 28, vertebral_number)) %>%
  group_by(implant, side) %>%
  mutate(implant_number = row_number()) %>%
  arrange(vertebral_number, implant_number)

 
implants_all_df <- vertebral_number_df %>%
  left_join(implant_starts_df) %>%
  pivot_wider(names_from = side, values_from = x) %>%
  mutate(implant = as_factor(implant)) %>%
  mutate(implant = fct_relevel(implant, c("occipital_screw", "pedicle_screw", "pelvic_screw", "pars_screw", "lateral_mass_screw", "translaminar_screw", "laminar_downgoing_hook", "laminar_upgoing_hook", "tp_hook")))%>%
  pivot_longer(cols = c(left, right), names_to = "side", values_to = "x") %>%
    arrange(side, implant) %>%
  remove_empty() %>%
  select(level, vertebral_number, implant, side, x, y, angle, length, width)
  

implants_all_df


  
  implant_factor <- c("occipital_screw", "pedicle_screw", "pelvic_screw", "pars_screw", "lateral_mass_screw", "translaminar_screw", "laminar_downgoing_hook", "laminar_upgoing_hook", "tp_hook")

```
```{r}

implants_wide_df <- implant_starts_df %>%
  select(level, implant, side) %>%
  filter(implant == "pedicle_screw") %>%
  pivot_wider(names_from = side, values_from = implant)

sum(str_count(string = implants_wide_df$level, pattern = "l1"))

str_detect(string = print(cat(implants_wide_df$level)), pattern = "t12")

vector <- Reduce(paste, implants_wide_df$level)

vector

str_count(string = Reduce(paste, implants_wide_df$level), pattern = "s2")

    make_ui <-  function(screw_level, selected = NULL){
        screw_label <- str_replace_all(string = screw_level, pattern = "_", replacement = " ")
        
        screw_label <- str_to_title(screw_label)
        
        radioGroupButtons(
            inputId = screw_level,
            label = screw_label,
            choices = c("Poly", "Uni", "Mono", "Reduction"),
            selected = selected, 
            size = "xs"
        )}

level_side_df <- implant_starts_df %>%
            select(vertebral_number, level, side, implant) %>%
            filter(implant == "pedicle_screw") %>%
            mutate(level_side = paste(level, side, implant, sep = "_")) %>%
            select(vertebral_number, level, side, level_side, implant) %>%
            arrange(vertebral_number)


ui_wide_df <- level_side_df %>%
  filter(level_side != "c3_right_pedicle_screw") %>%
  mutate(input_u = map(.x = level_side, .f = ~make_ui(screw_level = .x))) %>%
  select(level, side, input_u) %>%
  pivot_wider(names_from = side, values_from = input_u)

ui_wide_df %>%
  mutate(right_null = map(.x = right, .f = ~length(.x))) %>%
  unnest(right_null) %>%
  mutate(right = map(.x = right, .f = ~if_else(right_null == 0, , (.x))))

length(ui_wide_df$left)

summary(ui_wide_df$right[1])



length(ui_wide_df$right[][[1]])

ui_wide_df
is_vector(ui_wide_df)

level_side_df %>%
  filter(level_side != "c2_left_pedicle_screw") %>%
            select(level_side, side, vertebral_number) %>%
            pivot_wider(names_from = side, values_from = level_side) 

test_df <- level_side_df %>%
  filter(level_side %in% c("t9_right_pedicle_screw", "t10_right_pedicle_screw", "t10_left_pedicle_screw", "t11_left_pedicle_screw")) %>%
            select(vertebral_number, level_side, side) %>%
            pivot_wider(names_from = side, values_from = level_side)


test_df

```



```{r}
    make_ui_rows <-  function(left_screw_level = NULL, right_screw_level = NULL, left_selected = NULL, right_selected = NULL){
        ##LEFT
        left_screw_label <- str_replace_all(string = left_screw_level, pattern = "_", replacement = " ")
        
        left_screw_label <- str_to_title(left_screw_label)
        ## RIGHT
        right_screw_label <- str_replace_all(string = right_screw_level, pattern = "_", replacement = " ")
        
        right_screw_label <- str_to_title(right_screw_label)
        
        fixedRow(
            column(width = 12,
                   if(!is.null(left_screw_level)){
                   radioGroupButtons(
                       inputId = left_screw_level,
                       label = left_screw_label,
                       choices = c("Poly", "Uni", "Mono", "Reduction"),
                       selected = left_selected, 
                       size = "xs"
                   )
                       }
                   ),
            if(!is.null(right_screw_level)){
            column(width = 12,
                   
                       radioGroupButtons(
                           inputId = right_screw_level,
                           label = right_screw_label,
                           choices = c("Poly", "Uni", "Mono", "Reduction"),
                           selected = right_selected, 
                           size = "xs"
                       )
            )
                   }
                   
        )
        
    }

test_df <- level_side_df %>%
  filter(level_side %in% c("t9_right_pedicle_screw", "t10_right_pedicle_screw", "t10_left_pedicle_screw", "t11_left_pedicle_screw")) %>%
            select(vertebral_number, level_side, side) %>%
            pivot_wider(names_from = side, values_from = level_side)
  # mutate(ui_pic = list(make_ui_rows(left_screw_level = left, right_screw_level = right)))



mutate(x = if_else(is_vector(test_df$left), left, "no"))

is_vector(test_df$right)

if(is_vector(test_df$right)){
  right_v <- test_df$right
}else{
  right_v <- NULL
}

if(is_vector(test_df$left)){
  left_v <- test_df$left
}else{
  left_v <- NULL
}


test_list <- pmap(.l = list(..1 = left_v,
                       ..2 = right_v),
             .f = ~make_ui_rows(left_screw_level = ..1, right_screw_level = ..2, left_selected = NULL, right_selected = NULL))

test_list

st_long <- implant_starts_df %>%
              select(vertebral_number, level, side, implant) %>%
            filter(implant == "pedicle_screw") %>%
            distinct() %>%
            mutate(level_side = paste(level, side, implant, sep = "_")) %>%
            select(vertebral_number, level, side, level_side, implant) %>%
            arrange(vertebral_number) %>%
            select(vertebral_number, level, level_side, side)

st_long$side["left"]

match(x = "left", table = st_long$side)

        pmap(.l = list(..1 = (implant_starts_df ),
                       ..2 = left_vector,
                       ..3 = right_vector),
                          .f = ~make_ui_rows(level = ..1, left_screw_level = ..2, right_screw_level = ..3, left_selected = NULL, right_selected = NULL))
        

glue_collapse(names(implant_starts_df), sep = " ")
                
if(str_detect(string = glue_collapse(names(implant_s54tarts_df)), pattern = "level")){
  print("falsely printing")
}else{
  print("correct")
}
  str_detect(string = glue_collapse(names(implassnt_starts_df)), pattern = "level")  
  
  implant_starts_df %>%
    select(level, implant, side) %>%
    filter(implant == "pedicle_screw") %>%
    mutate(side_is_left = str_detect(side, "left")) %>%
    pivot_wider(names_from = side, values_from = implant)
    
 test_df <-  implant_starts_df %>%
    select(vertebral_number, level, side, implant) %>%
    filter(implant == "pedicle_screw") %>%
    distinct() %>%
    mutate(level_side = paste(level, side, implant, sep = "_")) %>%
    filter(level_side %in% c("c2_left_pedicle_screw", "c3_left_pedicle_screw", "c3_right_pedicle_screw", "c4_right_pedicle_screw")) %>%
  arrange(vertebral_number) %>%
    select(level, vertebral_number, level_side, side) %>%
    pivot_wider(names_from = side, values_from = level_side)
  
 
test_df %>%
  mutate(right = if_else(is.na(right), "no_screw", right))
 
dftest_names <- glue_collapse(names(test_df), sep = " ")
dftest_names

if(str_detect(string = dftest_names, pattern = "right")){
  print("id'd names correctly")
}else{
  test <- test_df %>%
    mutate(right )
}




```


```{r}
implant_starts_df %>%
  arrange(vertebral_number)

implant_starts_df$level[[1]]

test <- implant_starts_df %>%
  select(level, vertebral_number) %>%
  distinct() %>%
  arrange(vertebral_number) %>%
  mutate(level = fct_inorder(level))

test
tail(test$level, n = 1)

left_primary_rod <-  c("t10", "l3")

left_primary_rod[[2]]

range <- vertebral_number_df %>%
  mutate(uiv = left_primary_rod[1]) %>%
  mutate(liv = left_primary_rod[2]) %>%
  filter(level == uiv | level == liv) %>%
  distinct()

range
is_double(upper_rod_level)

upper_rod_level <- match(x = left_primary_rod[[1]], table = vertebral_number_df$level)
lower_rod_level <- match(x = left_primary_rod[[2]], table = vertebral_number_df$level)

vertebral_number_df %>%
  filter(between(vertebral_number, upper_rod_level, lower_rod_level))
  
  filter(between(vertebral_number, min(range$vertebral_number), max(range$vertebral_number)))

vertebral_number_df$level["t10":"l2"]

vertebral_number_df

        upper_rod_level <- match(x = input$left_primary_rod[[1]], table = left_rod_range_df$level)
        
        lower_rod_level <- match(x = input$left_primary_rod[[2]], table = left_rod_range_df$level)
        
        left_rod_matrix <- tibble(level = left_rod_range_df$level) %>%
            left_join(left_rod_range_df) %>%
            select(x, y) %>%
            as.matrix()
        
        
implant_starts_df %>%
  filter(side == "left") %>%
  select(level, vertebral_number, x, y) %>%
  mutate(upper_level_number = as.double(upper_rod_level),
         lower_level_number = as.double(lower_rod_level)) %>%
  filter(between(vertebral_number, upper_level_number, lower_level_number)) %>%
  select(x, y) %>%
  arrange(y)

implant_starts_df %>%
            select(level, vertebral_number) %>%
            distinct() %>%
            arrange(vertebral_number) 

vertebral_number_df$level

vertebral_number_df$level[c(1, length(vertebral_number_df$level))]

c(vertebral_number_df$level[1], tail(vertebral_number_df$level, n = 1))

is.finite(asdfas)

is.na(dsc)

unique(vertebral_number_df$level)[1]

implant_starts_df

build_rod_function <- function(range, side, add_medial_or_lateral = "medial", full_range_possible_df, x_offset = 0.003){
  upper_level <- range[1]
  lower_level <- range[2]
  
  if(side == "left"){
    x_modifier <- if_else(add_medial_or_lateral == "medial", x_offset, -x_offset)
  }else{
    x_modifier <- if_else(add_medial_or_lateral == "medial", -x_offset, x_offset)
  }
  
  number_range_for_rod_df <- full_range_possible_df %>%
    select(level, vertebral_number) %>%
    mutate(upper_level = upper_level, lower_level = lower_level) %>%
    filter(level == upper_level | level == lower_level) %>%
    distinct() %>%
    select(vertebral_number)
  
  rod_matrix <- full_range_possible_df %>%
    filter(between(vertebral_number, number_range_for_rod_df$vertebral_number[1], number_range_for_rod_df$vertebral_number[2])) %>%
    select(x, y) %>%
    arrange(y) %>%
    distinct() %>%
    mutate(x = x + x_modifier) %>%
    as.matrix()
  
  rod_sf <- st_buffer(st_linestring(rod_matrix), dist = 0.003, endCapStyle = "ROUND")
  
}

rod_x <- build_rod_function(range = c("T10", "L4"), side = "left", add_medial_or_lateral = "medial", full_range_possible_df = implant_starts_df %>% filter(side == "left"))

ggplot() + 
  geom_sf(data =  rod_x)

range <- c("T10", "L4")

range[1]

summary(rod_y)[1]

length(rod_x)

sat_rods_level_range_df <- tibble(level = range) %>%
  left_join(implant_starts_df) %>%
  filter(implant == "pedicle_screw", side == "left") %>%
  select(vertebral_number)

sat_rods_levels_df <- implant_starts_df %>%
  filter(between(vertebral_number, min(sat_rods_level_range_df$vertebral_number), max(sat_rods_level_range_df$vertebral_number))) %>%
  filter(implant == "pedicle_screw", side == "left")

main_rod_levels <- implant_starts_df %>%
  filter(implant == "pedicle_screw", side == "left") %>%
  anti_join(sat_rods_levels_df)

r_vector <- c("C2", "C3")

range_to_filter_out_test_df <- tibble(level = c("C2", "C3"))

str_to_lower(string = r_vector)

implant_starts_df %>%
  anti_join(range_to_filter_out_test_df)

tabyl(implant_starts_df$implant)

```

```{r, fig.height=9}
ggdraw() +
      draw_image(spine_png, scale = 2, y = 0, valign = 0, x = 0, width = 1, interpolate = TRUE) +
      draw_text(text = labels_df$labels, x = labels_df$x_left, y = labels_df$y, size = 12, fontface = "bold") +
      draw_text(text = labels_df$labels, x = labels_df$x_right, y = labels_df$y, size = 12, fontface = "bold") +
      geom_point(aes(x = 0.5 - iliac_x_offset, y = iliac_y), size = 4) + 
  geom_point(aes(x = 0.5 - s2ai_x_offset, y = s2ai_y), size = 4) + 
  # geom_sf(data = l2_upgoing_hooks_collection) +
  # ggpattern::geom_sf_pattern(data = s2ai_screw_screwhead$left_screw_sf, pattern = "stripe",  pattern_fill = "red",alpha = 0.8, pattern_colour = "blue", pattern_density = 0.01, pattern_spacing = 0.003, angle = 70) +
  # ggpattern::geom_sf_pattern(data = s2ai_screw_screwhead$right_screw_sf, pattern = "stripe",  pattern_fill = "red",alpha = 0.8, pattern_colour = "blue", pattern_density = 0.01, pattern_spacing = 0.003, angle = 70) +
  theme_minimal_grid()  +
  ylim(0, 0.5)

plot <- ggdraw() +
  draw_image(image = spine_png, x = 0, y = 0, width = 1, valign = 0, clip = "off",  interpolate = FALSE) + 
  geom_sf(data = decompression_levels_sf)

plot

laminectomy_points_df <- read_csv("coordinates_laminectomy.csv")

laminectomy_points_df

ggdraw(plot, clip = "on") + 
  ylim(0.1, 0.5)

implant_starts_df %>%
  # select(level, vertebral_number) %>%
  arrange(vertebral_number) %>%
  # distinct() %>%
  mutate(level = fct_inorder(level))

spine_levels

implant_starts_df

test <- tibble(level = c("C3", "C5"), side = "left")

test %>%
  left_join(implant_starts_df)

implant_starts_df %>%
  mutate(level_side = paste(level, side, implant, sep = "_")) %>%
  select(level, level_side, side) %>%
  filter(level_side %in% c("L1_right_pedicle_screw", "L3_right_pedicle_screw", "L1_left_pedicle_screw", "L2_left_pedicle_screw", "L5_right_pedicle_screw")) %>%
  pivot_wider(names_from = side, values_from = level_side)


```

```{r}
implants_wide_df <- implant_starts_df %>%
  mutate(level_side = paste(level, side, implant, sep = "_")) %>%
  select(level, level_side, side) %>%
  filter(level_side %in% c("L1_right_pedicle_screw", "L3_right_pedicle_screw", "L1_left_pedicle_screw", "L2_left_pedicle_screw", "L5_right_pedicle_screw")) %>%
  pivot_wider(names_from = side, values_from = level_side)
implants_wide_df

df_names <- glue_collapse(names(implants_wide_df), sep = " ")

df_names

level_vector <- implants_wide_df$level

level_vector

## the data frame can't have any missing values, otherwise the vectors will be of different lengths when you run map()
if(str_detect(string = df_names, pattern = "left")){
  implants_wide_df <- implants_wide_df %>%
    mutate(left = if_else(is.na(left), "no_screw", left))
  
  left_vector <- implants_wide_df$left
}else{
  left_vector <- implants_wide_df$no_screw_vector
}

if(str_detect(string = df_names, pattern = "right")){
  implants_wide_df <- implants_wide_df %>%
    mutate(right = if_else(is.na(right), "no_screw", right))
  
  right_vector <- implants_wide_df$right
}else{
  right_vector <- implants_wide_df$no_screw_vector
}

max_levels <- nrow(implants_wide_df)     
levels_count <- seq(from = 1, to = max_levels, by = 1)

left_vector
right_vector
```




```{r}
build_laminectomy_function <- function(start_x = 0.5, width, superior_y, inferior_y){
  left_inferior_x <- start_x - 0.5*width
  left_superior_x <- start_x - 0.4*width
  right_inferior_x <- start_x + 0.5*width
  right_superior_x <- start_x + 0.4*width
  
  laminectomy <- st_buffer(st_polygon(list(rbind(c(left_inferior_x, inferior_y),
                                  c(left_superior_x, superior_y),
                                  c(right_superior_x, superior_y),
                                  c(right_inferior_x, inferior_y),
                                  c(left_inferior_x, inferior_y)
    
  ))), dist = 0.004, endCapStyle = "SQUARE")
  # laminectomy
  st_buffer(laminectomy, dist = -0.003, endCapStyle = "SQUARE")
}

laminectomy_constructed_df <- laminectomy_points_df %>%
  mutate(decompression_constructed = pmap(list(..1 = width, 
                                               ..2 = superior_y,
                                               ..3 = inferior_y), .f = ~build_laminectomy_function(start_x = 0.5, width = ..1, superior_y = ..2, inferior_y = ..3)))


decompression_levels_sf <- st_multipolygon(laminectomy_constructed_df$decompression_constructed)

 ggdraw() +
  draw_image(image = spine_png, x = 0, y = 0, width = 1, valign = 0, clip = "off") + 
                   ggpattern::geom_sf_pattern(
                    data = decompression_levels_sf,
                    pattern = "stripe",
                    pattern_fill = "grey",
                    alpha = 0.8,
                    pattern_colour = "red",
                    pattern_density = 0.02,
                    pattern_spacing = 0.1
                   )

```



```{r}

implant_starts_df %>%
  filter(implant == "tether", level %in% c("L4", "T10", "T4", "T6"))

tethers_df <- implant_starts_df %>%
  filter(implant == "tether") %>%
  mutate(tether_implants = map2(.x = y, .y = length, .f = ~tether_function(tether_start_y = .x, tether_length = .y)))

t4_tether <- tether_function(tether_start_y = 0.671, tether_length = 0.029)

t6_tether <- tether_function(tether_start_y = 0.610, tether_length = 0.032)

l4_tether <- tether_function(tether_start_y = 0.26, tether_length = 0.036)

t10_tether <- tether_function(tether_start_y = 0.48, tether_length = 0.035)

tethers_sf <- st_multilinestring()


summary(tethers_df$tether_implants)
tethers_sf <- st_multipolygon(tethers_df$tether_implants)

 ggdraw() +
  draw_image(image = spine_png, x = 0, y = 0, width = 1, valign = 0, clip = "on") + 
                   # ggpattern::geom_sf_pattern(
                   #  data = decompression_levels_sf,
                   #  pattern = "stripe",
                   #  pattern_fill = "grey",
                   #  alpha = 0.8,
                   #  pattern_colour = "red",
                   #  pattern_density = 0.02,
                   #  pattern_spacing = 0.1
                   # )
   geom_sf(data = tethers_sf)
 
 tethers_wires_df <- tibble(implant = character(), 
                                              level = character(),
                                              vertebral_number = numeric(),
                                              x = numeric(),
                                              y = numeric(),
                                             length = numeric())
                            
tethers_wires_df

```
```{r}
#pedicle hooks
implant_starts_df %>%
  filter(implant == "pedicle_screw")

build_pedicle_hook_function <- function(x_start, y_start){
  
  y_lenth <- 0.01
  
  x_width <- 0.012
  
  if(x_start < 0.5){
    start <- c(x_start, y_start)
    
    point_2 <- c(start[1], start[2] - y_lenth)
    
    point_3 <- c(start[1] + x_width*0.5, start[2] - y_lenth)
    
    point_4 <- c(point_3[1], point_3[2] + y_lenth*0.75)
    
    point_5 <- point_3
    
    point_6 <- c(point_2[1] + x_width, point_2[2])
    
    point_7 <- c(point_6[1], point_6[2] + y_lenth*0.75)
    
    hook <- st_linestring(rbind(start, point_3, point_4, point_5, point_6, point_7))
    
    hook_sf <- st_buffer(hook, dist = 0.002, endCapStyle = "ROUND")
  }
  
    if(x_start > 0.5){
    start <- c(x_start, y_start)
    
    point_2 <- c(start[1], start[2] - y_lenth)
    
    point_3 <- c(start[1] - x_width*0.5, start[2] - y_lenth)
    
    point_4 <- c(point_3[1], point_3[2] + y_lenth*0.75)
    
    point_5 <- point_3
    
    point_6 <- c(point_2[1] - x_width, point_2[2])
    
    point_7 <- c(point_6[1], point_6[2] + y_lenth*0.75)
    
    hook <- st_linestring(rbind(start, point_3, point_4, point_5, point_6, point_7))
    
    hook_sf <- st_buffer(hook, dist = 0.002, endCapStyle = "ROUND")
    }
  
  return(hook_sf)

}

implant_starts_df %>%
  filter(implant == "pedicle_hook")

pedicle_hook_df <- implant_starts_df %>%
  filter(implant == "pedicle_hook") %>%
  mutate(hook = pmap(list(..1 = x,
                          ..2 = y), .f = ~build_pedicle_hook_function(x_start = ..1, y_start = ..2)))

# osteotomies_sf <- st_multilinestring(osteotomy_df$grade_1)

hook_sf <- st_multipolygon(pedicle_hook_df$hook)

 ggdraw() +
  draw_image(image = spine_png, x = 0, y = 0, width = 1, valign = 0, clip = "on") + 
   geom_sf(data = hook_sf, color = "red")
```
```{r}
implant_starts_df %>%
  filter(implant == "sublaminar_wire")
```


```{r}
#sublaminar bands

implant_starts_df %>%
  filter(implant == "sublaminar_wire")

con <- st_linestring(rbind(c(0.515, 0.88), c(0.505, 0.89), c(0.515, 0.88), c(0.505, 0.87)))

sub <- st_linestring(rbind(c(0.50, 0.89), c(0.50, 0.87)))

con_b <- st_buffer(con, dist = .002)

sub_b <- st_buffer(sub, dist = 0.001)


con_sub <- st_polygon(st_union(x =con_b, y = sub_b))

sublaminar_band_df <- implant_starts_df %>%
  filter(implant == "sublaminar_wire") %>%
  filter(level == "T10" )  %>%
  mutate(sub_band = pmap(list(..1 = x, 
                              ..2 = y, 
                              ..3 = length, 
                              ..4 = implant), .f = ~ screw_hook_implant_function(implant_type = ..4, start_x = ..1, y = ..2, sublaminar_band_length = ..3)))


# osteotomies_sf <- st_multilinestring(osteotomy_df$grade_1)
sublaminar_band_df
sublaminar_band_sf <- st_multipolygon(sublaminar_band_df$sub_band)
sublaminar_band_sf

summary(sublaminar_band_df$sublaminar_band[1])

 ggdraw() +
  draw_image(image = spine_png, x = 0, y = 0, width = 1, valign = 0, clip = "on") + 
   # geom_sf(data = sublaminar_band_sf, color = "red") +
   # geom_sf(data = st_union(x =con_b, y = sub_b)) +
   geom_sf(data = sublaminar_band_sf) +
   # geom_sf(data = sub_b) +
   ylim(0.3, 0.9)
```




```{r}
schwab_points_df <- read_csv(file = "schwab_1_osteotomy.csv")


schwab_points_df

schwab_points_df %>%
  filter(grade == "Grade 1")
# decompressions_osteotomies_list$osteotomies


osteotomy_df <- schwab_points_df %>%
  filter(grade == "Grade 1") %>%
  mutate(osteotomy_constructed = pmap(list(..1 = level, 
                             ..2 = grade,
                             ..3 = lateral_x,
                             ..4 = superior_y,
                             ..5 = medial_x,
                             ..6 = inferior_y), .f = ~build_osteotomy_function(level = ..1,
                                                                               osteotomy_grade = ..2,
                                                                               lateral_x = ..3,
                                                                               superior_y = ..4,
                                                                               medial_x = ..5, 
                                                                               inferior_y = ..6)))
# ost_sf <- st_geometrycollection(osteotomy_df$grade_3)

grade_1_df <- osteotomy_df %>%
  filter(grade == "Grade 1")

grade_2_df <- osteotomy_df %>%
  filter(grade == "Grade 2")

grade_2_df

grade_3_df <- osteotomy_df %>%
  filter(grade == "Grade 3")

grade_1_sf <- st_multilinestring(grade_1_df$osteotomy_constructed)

if(nrow(grade_2_df) > 0){
  grade_2_sf <- st_multipolygon(grade_2_df$osteotomy_constructed)
}else{
  grade_2_sf <- NULL
}

grade_2_sf

grade_2_sf <- st_multipolygon(grade_2_df$osteotomy_constructed)

grade_3_sf <- st_multipolygon(grade_3_df$osteotomy_constructed)

grade_2_sf <- NULL

 ggdraw() +
  draw_image(image = spine_png, x = 0, y = 0, width = 1, valign = 0, clip = "on") + 
   # geom_sf(data = osteotomies_sf, color = "red")
            ggpattern::geom_sf_pattern(
                data = grade_2_sf, # left_implants_constructed_reactive_sf(),
                pattern = "crosshatch",
                alpha = 0.8,
                pattern_colour = "red",
                pattern_fill = "black",
                pattern_density = 0.02,
                pattern_spacing = 0.01,
                pattern_angle = 70
            )
 
 
 
 implant_starts_df

```
```{r}
all_implants_constructed_main_rod_df <-  implant_starts_df %>%
  filter(implant != "tether") %>%
  mutate(rod = "satellite_rod") %>%
  mutate(sublaminar_band_length = length) %>%
    replace_na(list(length = 0, width = 0, angle = 0)) %>%
  mutate(implant_constructed = pmap(.l =  list(..1 = implant, 
                                               ..2 = x, 
                                               ..3 = y, 
                                               ..4 = angle,
                                               ..5 = length, 
                                               ..6 = width,
                                               ..7 = rod, 
                                               ..8 = sublaminar_band_length), .f = ~ screw_hook_implant_function(implant_type = ..1, 
                                                                                                                 main_or_sattelite_rod = ..7, 
                                                                                                                 start_x = ..2,
                                                                                                                 y = ..3,
                                                                                                                 angle = ..4,
                                                                                                                 screw_length_mod = ..5,
                                                                                                                 screw_width_mod = ..6, 
                                                                                                                 sublaminar_band_length = ..8)))

all_implants_constructed_satellite_rod_df <-  implant_starts_df %>%
  filter(implant != "tether") %>%
  mutate(rod = "satellite_rod") %>%
  mutate(sublaminar_band_length = length) %>%
  replace_na(list(length = 0, width = 0, angle = 0)) %>%
  mutate(implant_constructed = pmap(.l =  list(..1 = implant, 
                                               ..2 = x, 
                                               ..3 = y, 
                                               ..4 = angle,
                                               ..5 = length, 
                                               ..6 = width,
                                               ..7 = rod, 
                                               ..8 = sublaminar_band_length), .f = ~ screw_hook_implant_function(implant_type = ..1, 
                                                                                                                 main_or_sattelite_rod = ..7, 
                                                                                                                 start_x = ..2,
                                                                                                                 y = ..3,
                                                                                                                 angle = ..4,
                                                                                                                 screw_length_mod = ..5,
                                                                                                                 screw_width_mod = ..6, 
                                                                                                                 sublaminar_band_length = ..8)))


all_implants_constructed_df <- all_implants_constructed_main_rod_df %>%
  union_all(all_implants_constructed_satellite_rod_df)

all_implants_constructed_df
```



```{r}

all_implants_sf <- st_geometrycollection(all_implants_constructed_df$implant_constructed)

all_implants_sf <- st_multipolygon(all_implants_constructed_df$implant_constructed)


 ggdraw() +
  draw_image(image = spine_png, x = 0, y = 0, width = 1, valign = 0, clip = "on") + 
   geom_sf(data = all_implants_sf, color = "red")
            ggpattern::geom_sf_pattern(
                data = grade_2_sf, # left_implants_constructed_reactive_sf(),
                pattern = "crosshatch",
                alpha = 0.8,
                pattern_colour = "red",
                pattern_fill = "black",
                pattern_density = 0.02,
                pattern_spacing = 0.01,
                pattern_angle = 70
            )


```




```{r}
l1_df_right <- read_csv(file = "l1_body.csv")

l1_df <- l1_df_right %>%
  mutate(x = 1-x) %>%
  union_all(l1_df_right) %>%
  select(coordinate_type, x, y) %>%
  mutate(x = round(x, 2), y = round(y, 2))

l1_matrix <- l1_df%>%
  bind_rows(l1_df[1,]) %>%
  select(x, y) %>% as.matrix()

l1_matrix



l1_line<- st_multipoint(x = l1_matrix )

l1_buffered <- st_union(l1_line)

l1_sf <- st_polygon(list(l1_buffered))

l1_buffered <- st_buffer(st_boundary(l1_buffered), dist = 0.005, endCapStyle = "ROUND")

ggplot() + 
  geom_sf(data = st_buffer(l1_sf, dist =  0.005))
  ggpattern::geom_sf_pattern(data = l1_buffered, pattern = "plasma", pattern_alpha = 1, pattern_scale = 2, color = "black")

```

```{r}
spine_png <- image_read(path = "posterior_spine_figure.png")


```

