---
title: "R Notebook"
output: html_notebook
---

## create a test dataframe
```{r}
tlif_test_df <- all_implants_constructed_df %>%
  filter(approach == "posterior") %>%
  filter(object == "tlif" | object == "sublaminar_decompression" | object == "grade_2") %>%
  filter(level == "L3-L4" | level == "L4-L5") %>%
  filter(side == "left" | side == "central")

iliac_test_df <- all_implants_constructed_df %>%
  filter(approach == "posterior") %>%
  filter(level  == "Iliac") %>%
  select(level, vertebral_number, approach, category, object, side) %>%
  distinct()

iliac_test_df

l2_hook_test_df <- all_implants_constructed_df %>%
  filter(approach == "posterior") %>%
  filter(level  == "L2") %>%
  filter(object == "laminar_downgoing_hook") 

lumbar_test_df <- all_implants_constructed_df %>%
  filter(approach == "posterior") %>%
  filter(level %in% c("L3", "L4", "l5")) %>%
  filter(object == "pedicle_screw" | object == "cement_augmentation")  %>%
  union_all(l2_hook_test_df) %>%
  union_all(tlif_test_df) %>%
  union_all(iliac_test_df) %>%
  distinct()


lumbar_test_df

revision_decompression_test_df <- open_canal_df %>%
  filter(level %in% c("L3"))

levels_numbered_df

labels_df

test_pso_vector <- c("T8", "T9", "T10", "T11", "L1", "L2", "L4", "L5")

test_pso_vector_df <- tibble(level = test_pso_vector)

test_vector_numbered_df <-  test_pso_vector_df %>%
  left_join(levels_numbered_df)

pso_level_test_df <- tibble(vertebral_number = as.double(seq(from = min(test_vector_numbered_df$vertebral_number), to = max(test_vector_numbered_df$vertebral_number)))) %>%
  left_join(test_vector_numbered_df) %>%
  filter(is.na(level)) %>%
  select(vertebral_number) %>%
  filter(vertebral_number == max(vertebral_number)) %>%
  left_join(levels_numbered_df)

pso_level_test_df$level

pso_test_list <- identify_cranial_caudal_interspace_body_list_function(level = pso_level_test_df$level)

pso_test_list$cranial_level


interbody_levels_df

test_df <- all_implants_constructed_df %>%
  filter(approach == "anterior") %>%
  # select(level, vertebral_number, object) %>%
  filter(between(vertebral_number, 22, 23)) %>%
  # filter(object != "screw_washer") %>%
  # filter(object != "disk_arthroplasty") %>%
  distinct()
  tabyl(object)
  
anterior_fusion_levels_function <- function(all_objects_added_df){
  anterior_fusion_implants_df <- all_objects_added_df %>%
    filter(approach == "anterior") %>%
    select(level, vertebral_number, object) %>%
    filter(object != "screw_washer") %>%
    filter(object != "disk_arthroplasty") %>%
    distinct()
  
  corpectomy_df <- anterior_fusion_implants_df %>%
    filter(str_detect(string = object, pattern = "corpectomy")) %>%
    select(level, object) %>%
    distinct() %>%
    mutate(level = map(.x = level, .f = ~ identify_cranial_caudal_interspace_body_list_function(level = .x))) %>%
  unnest() %>%
  unnest() %>%
  filter(str_detect(string = level, pattern = "-")) %>%
  left_join(levels_numbered_df) %>%
  mutate(object = "fusion") %>%
  distinct()
  
  fusion_levels_df <- anterior_fusion_implants_df %>%
    union_all(corpectomy_df) %>%
    filter(str_detect(level, pattern = "-")) %>%
    mutate(object = "fusion") %>%
    distinct() %>%
    arrange(vertebral_number)
  
  return(fusion_levels_df)
  
}
```




```{r}

arthroplasty_df <- implant_starts_df %>%
  filter(object == "anterior_disc_arthroplasty") %>%
  filter(level == "C4-C5") %>%
  remove_empty()

arthroplasty_df

# matrix(c(3,1), c(5,1), c(4,2), c(3,1))
# 
# st_linestring(matrix(c(3, 5, 4, 3), c(1, 1, 2, 1)))
# 
# st_polygon(list(st_linestring(matrix(c(3, 5, 4, 3), c(1, 1, 2, 1)))))
# 
# test_point <- st_buffer(x = st_point(x = c(1,1)), dist = 2, singleSide = FALSE)
# 
# test_poly <- st_buffer(x = st_zm(st_polygon(st_linestring(matrix(c(3, 5, 4, 3), c(1, 1, 2, 1))))), dist = 1)
# 
# test_poly <-  st_buffer(st_polygon(list(rbind(c(3,1), c(5,1), c(4,2), c(3,1)))), dist = 1, endCapStyle = "FLAT")

arthroplasty_function <- function(y_for_inferior_endplate, y_for_superior_endplate, endplate_width){
  endplate_height <- y_for_inferior_endplate - y_for_superior_endplate
  
  left_bottom_point <- c(0.5 - endplate_width/2, y_for_superior_endplate)
  right_bottom_point <- c(0.5 + endplate_width/2, y_for_superior_endplate)
  bottom_top_point <- c(0.5, y_for_superior_endplate + endplate_height/2)
  
  top_left_point <- c(0.5 - endplate_width/2, y_for_inferior_endplate)
  top_right_point <- c(0.5 + endplate_width/2, y_for_inferior_endplate)
  
  bottom_half_sf <- st_buffer(st_polygon(list(rbind(left_bottom_point, right_bottom_point, bottom_top_point, left_bottom_point))), dist = endplate_height*0.2)
  
  full_disc_sf <- st_buffer(st_polygon(list(rbind(left_bottom_point, right_bottom_point, top_right_point, top_left_point, left_bottom_point))), dist = endplate_height*0.1)
  
  top_disc_buff <- st_buffer(st_difference(x = full_disc_sf, y = bottom_half_sf), dist = -0.0003)
  
  disc_total <- st_union(x = top_disc_buff, y = bottom_half_sf)
  
  return(disc_total)
}


test_bottom_sf <- arthroplasty_function(y_for_inferior_endplate = 0.87, y_for_superior_endplate = 0.865, endplate_width = 0.013)

top_disc <- st_difference(x = test_bottom_sf$full_disc_sf, y = test_bottom_sf$bottom_half_sf)

top_disc_buff <- st_buffer(top_disc, dist = -0.0003)

disc_total <- arthroplasty_function(y_for_inferior_endplate = 0.87, y_for_superior_endplate = 0.865, endplate_width = 0.013)


all_implants_constructed_df 
  filter(approach == "Anterior")


ggplot() + 
  # geom_sf(data = top_disc_buff) +
  # geom_sf(data = test_bottom_sf$full_disc_sf) +
  # geom_sf(data = test_bottom_sf$bottom_half_sf)+
  geom_sf(data = disc_total)

```

```{r}
anterior_df

anterior_objects_df_test <- anterior_df %>%
  mutate(object_constructed = pmap(list(..1 = object,
                                        ..2 = width,
                                        ..3 = inferior_endplate_y,
                                        ..4 = superior_endplate_y, 
                                        ..5 = superior_enplate_inferior_body_y, 
                                        ..6 = inferior_endplate_superior_body_y),
                                   .f = ~ anterior_implant_function(object_type = ..1, 
                                                                    body_width = ..2,
                                                                    inferior_endplate_y = ..3,
                                                                    superior_endplate_y = ..4,
                                                                    superior_endplate_inferior_body_y = ..5, 
                                                                    inferior_endplate_superior_body_y = ..6)))

all_implants_constructed_df

c456_test <- all_implants_constructed_df %>%
  # filter(object == "anterior_disc_arthroplasty") %>%
  filter(level == "C4-C5" | level == "C5-C6") 

c456_test

test_sf <- st_multipolygon(x = c456_test$object_constructed)

full_list <- append(c456_test$object_constructed)

full_list <- c456_test$object_constructed

c456_test$object_constructed

c456_test

c456_test %>% filter(object == "anterior_disc_arthroplasty") 
  
  object_constructed

test_c456_sf <- st_multipolygon((c456_test$object_constructed))
c456_test%>% filter(object == "anterior_disc_arthroplasty") %>%
    unnest()

test2 <- st_multipolygon((c456_test%>% filter(object == "anterior_disc_arthroplasty") %>% unnest())$object_constructed)

ggplot() + 
  # geom_sf(data =  c45_test$object_constructed[[1]]) +
  # geom_sf(data = test2) +
                  # ggpattern::geom_sf_pattern(
                  #   data =  test2,
                  #   pattern = "plasma",
                  #   pattern_fill = "grey90",
                  #   fill = "#7899F5",
                  #   pattern_spacing = 0.01,
                  #   pattern_density = 0.7)
                    ggpattern::geom_sf_pattern(
                    data =  test2,
                    color = "darkblue",
                    size = 3,
                    pattern = "stripe",
                    pattern_fill = "blue",
                    pattern_colour = "grey90",
                    pattern_angle = 0,
                    pattern_spacing = 0.01,
                    pattern_density = 0.9)

```
```{r}

arthroplasty_function2 <- function(y_for_inferior_endplate, y_for_superior_endplate, endplate_width){
  endplate_height <- y_for_inferior_endplate - y_for_superior_endplate

  # bottom_circle_point <- st_point(c(0.5, y_for_inferior_endplate))
  
  bottom_oval <- st_ellipse(st_point(c(0.5, y_for_superior_endplate)), ex = endplate_width/2, ey = endplate_height*0.75)
  
  left_bottom_point <- c(0.5 - endplate_width/2, y_for_superior_endplate)
  right_bottom_point <- c(0.5 + endplate_width/2, y_for_superior_endplate)
  # bottom_top_point <- c(0.5, y_for_superior_endplate + endplate_height/2)
  
  top_left_point <- c(0.5 - endplate_width/2, y_for_inferior_endplate)
  top_right_point <- c(0.5 + endplate_width/2, y_for_inferior_endplate)
  
  full_disc_sf <- st_buffer(st_polygon(list(rbind(left_bottom_point, right_bottom_point, top_right_point, top_left_point, left_bottom_point))), dist = endplate_height*0.1)
  
  
  top_disc_buff <- st_buffer(st_difference(x = full_disc_sf, y = bottom_oval), dist = -0.0004)
  
  bottom_disc_buff <- st_buffer(st_intersection(x = bottom_oval, y = full_disc_sf), dist = -0.0004)
  
  disc_total <- st_union(x = top_disc_buff, y = bottom_disc_buff)
  
  # disc_list <- list(top = top_disc_buff, bottom = st_buffer(bottom_oval, dist = -0.0004))
  
  return(disc_total)
}

  library(nngeo)
  
  oval_test <- st_ellipse(bottom_circle_point, ex = 0.014, ey = 0.008)
  
  ctest <- c456_test %>%
    filter(object == "anterior_disc_arthroplasty") %>%
    remove_empty() %>%
    select(-approach, -category)
  
  ctest
  
  bottom_circle_point <- st_point(c(0.5, 0.838))
  
  oval_test <- st_ellipse(bottom_circle_point, ex = 0.014/2, ey = 0.008)
  
  full_disc_test_sf <- arthroplasty_function2(y_for_inferior_endplate = 0.846, y_for_superior_endplate = 0.838, endplate_width = 0.014)
  
  ggplot() +
    geom_sf(data = full_disc_test_Sf) +
    geom_sf(data = oval_test) 
    # geom_sf(data = bottom_circle) + 
    geom_sf(data = full_disc_test_Sf)
    
    full_disc_test_sf
    
    ggplot() + 
      geom_sf(data = full_disc_test_sf) 
      geom_sf(data = full_disc_test_sf$bottom)
      
c56_test_df <- all_implants_constructed_df %>%
        filter(object == "anterior_disc_arthroplasty") %>%
        filter(level == "C5-C6") %>%
  select(level, object, object_constructed) 

c56_test_df %>%
  unnest() %>%
  mutate(object_constructed = st_zm(object_constructed)) 

unnest(c56_test_df$object_constructed)

ggplot() + 
  geom_sf(data = c56_test_df$object_constructed[[2]]) + 
  geom_sf(data = c56_test_df$object_constructed[[1]])
```
```{r}
arthroplasty_function2 <- function(y_for_inferior_endplate, y_for_superior_endplate, endplate_width){
  endplate_height <- y_for_inferior_endplate - y_for_superior_endplate
  
  # bottom_circle_point <- st_point(c(0.5, y_for_inferior_endplate))
  
  bottom_oval <- st_ellipse(st_point(c(0.5, y_for_superior_endplate)), ex = endplate_width/2, ey = endplate_height*0.75)
  
  left_bottom_point <- c(0.5 - endplate_width/2, y_for_superior_endplate)
  right_bottom_point <- c(0.5 + endplate_width/2, y_for_superior_endplate)
  # bottom_top_point <- c(0.5, y_for_superior_endplate + endplate_height/2)
  
  top_left_point <- c(0.5 - endplate_width/2, y_for_inferior_endplate)
  top_right_point <- c(0.5 + endplate_width/2, y_for_inferior_endplate)
  
  full_disc_sf <- st_buffer(st_polygon(list(rbind(left_bottom_point, right_bottom_point, top_right_point, top_left_point, left_bottom_point))), dist = endplate_height*0.1)
  
  
  top_disc_buff <- st_buffer(st_difference(x = full_disc_sf, y = bottom_oval), dist = -0.0004)
  
  bottom_disc_buff <- st_buffer(st_intersection(x = bottom_oval, y = full_disc_sf), dist = -0.0004)
  
  # disc_total <- st_union(x = top_disc_buff, y = bottom_disc_buff)
  
  # disc_list <- list(top = top_disc_buff, bottom = st_buffer(bottom_disc_buff, dist = -0.0004))
  
  # disc_list <- list(top = top_disc_buff, bottom = bottom_disc_buff[[1]])
  
  disc_df <- tibble(object_constructed = c(st_geometry(top_disc_buff), st_geometry(bottom_disc_buff[[1]]))) %>%
    mutate(color = c("lightblue", "blue"))
  
  return(disc_df)
}

full_disc_test_sf <- arthroplasty_function2(y_for_inferior_endplate = 0.846, y_for_superior_endplate = 0.838, endplate_width = 0.014)

test <- tibble(level = "C5-C6", object_constructed = full_disc_test_sf)

# st_polygonize(full_disc_test_sf$bottom)
# 
# full_disc_test_sf$bottom[[1]]
# 
# st_multipolygon(full_disc_test_sf$bottom)
# 
# st_as_sf(full_disc_test_sf$bottom)

ca_test_df <- all_implants_constructed_df %>%
  filter(object == "anterior_disc_arthroplasty") %>%
  filter(level == "C5-C6" | level == "C6-C7") %>%
  remove_empty() %>%
  unnest()

ca_test_empty <- tibble(object_constructed = c(), color = c())

ggplot() + 
  geom_sf(data = ca_test_empty, aes(geometry = object_constructed, fill = color)) + 
  scale_fill_identity()


test_vect <- c("Spinal Cord Monitoring", 
               "Intraoperative use of microscope for microdissection",
               "Use of stereotactic navigation system for pedicle screw placement",
               "Application of Cranial Tongs", 
               "Application of Halo", 
               "Application of Halo for thin skull osteology (e.g. pediatric)",
               "Removal of tongs or Halo applied by another inidividual",
               "Irrigation and Debridement",
               "Open Biopsy of vertebral body",
               "Repair of dural/CSF leak",
               "Dural Graft",
               "Removal of spinal instrumentation",
               "Exploration of spinal prior fusion",
               "Open treatment of vertebral fracture",
               "***Other***")

keep(.x = test_vect, .p = ~ str_detect(.x, "Biopsy") | 
       str_detect(.x, "Repair of dural/CSF")  | 
       str_detect(.x, "Dural")  | 
       str_detect(.x, "Removal of spinal") | 
       str_detect(.x, "Exploration of") | 
       str_detect(.x, "Open treatment"))

```



```{r}
# op_note_procedure_category_function <- function(object){
#   procedure_category <- case_when(
#     object == "cement_augmentation" ~ "vertebral cement augmentation",
#     object == "laminar_downgoing_hook" ~ "posterior spinal instrumentation",
#     object == "laminar_upgoing_hook" ~ "posterior spinal instrumentation",
#     object == "lateral_mass_screw" ~ "posterior spinal instrumentation",
#     object == "occipital_screw" ~ "occiput instrumentation",
#     object == "pars_screw" ~ "posterior spinal instrumentation",
#     object == "pedicle_hook" ~ "posterior spinal instrumentation",
#     object == "pedicle_screw" ~ "posterior spinal instrumentation",
#     object == "laminar_downgoing_hook" ~ "posterior spinal instrumentation",
#     object == "sublaminar_wire" ~ "posterior spinal instrumentation",
#     object == "tp_hook" ~ "posterior spinal instrumentation",
#     object == "translaminar_screw" ~ "posterior spinal instrumentation",
#     object == "pelvic_screw" ~ "pelvic instrumentation",
#     object == "tether" ~ "vertebral body posterior tethering",
#     object == "costovertebral_approach" ~ "decompression using a costovertebral approach",
#     object == "transpedicular_approach" ~ "decompression using a transpedicular approach",
#     object == "diskectomy" ~ "decompression",
#     object == "sublaminar_decompression" ~ "decompression",
#     object == "laminectomy" ~ "decompression",
#     object == "laminotomy" ~ "decompression",
#     object == "laminoplasty" ~ "laminoplasty",
#     object == "grade_1" ~ "inferior facetectomies",
#     object == "complete_facetectomy" ~ "complete facetectomies",
#     object == "grade_2" ~ "posterior column osteotomies",
#     object == "grade_3" ~ "pedicle subtraction osteotomy",
#     object == "grade_4" ~ "extended pedicle subtraction osteotomy",
#     object == "grade_5" ~ "vertebral column resection",
#     object == "no_implant_interbody_fusion" ~ "interbody fusion (without interbody implant)",
#     object == "llif" ~ "lateral lumbar interbody fusion and insertion of interbody device",
#     object == "plif" ~ "posterior lumbar interbody fusion and insertion of interbody device",
#     object == "tlif" ~ "transforaminal lumbar interbody fusion and insertion of interbody device"
#   )
#   procedure_category
# }

op_note_procedure_category_function <- function(object){
  procedure_category <- case_when(
    object == "cement_augmentation" ~ "vertebral cement augmentation",
    object == "laminar_downgoing_hook" ~ "posterior spinal instrumentation",
    object == "laminar_upgoing_hook" ~ "posterior spinal instrumentation",
    object == "lateral_mass_screw" ~ "posterior spinal instrumentation",
    object == "occipital_screw" ~ "occiput instrumentation",
    object == "pars_screw" ~ "posterior spinal instrumentation",
    object == "pedicle_hook" ~ "posterior spinal instrumentation",
    object == "pedicle_screw" ~ "posterior spinal instrumentation",
    object == "laminar_downgoing_hook" ~ "posterior spinal instrumentation",
    object == "sublaminar_wire" ~ "posterior spinal instrumentation",
    object == "tp_hook" ~ "posterior spinal instrumentation",
    object == "translaminar_screw" ~ "posterior spinal instrumentation",
    object == "pelvic_screw" ~ "pelvic instrumentation",
    object == "tether" ~ "vertebral body posterior tethering",
    object == "costovertebral_approach" ~ "decompression using a costovertebral approach",
    object == "revision_costovertebral_approach" ~ "revision and reexploration with decompression using a costovertebral approach",
    object == "transpedicular_approach" ~ "decompression using a transpedicular approach",
    object == "revision_transpedicular_approach" ~ "revision and reexploration with decompression using a transpedicular approach",
    object == "diskectomy" ~ "decompression",
    object == "sublaminar_decompression" ~ "decompression",
    object == "laminectomy" ~ "decompression",
    object == "laminotomy" ~ "decompression",
    object == "revision_diskectomy" ~ "revision and reexploration with decompression",
    object == "revision_sublaminar_decompression" ~ "revision and reexploration with decompression",
    object == "revision_laminectomy" ~ "revision and reexploration with decompression",
    object == "revision_laminotomy" ~ "revision and reexploration with decompression",
    object == "laminoplasty" ~ "laminoplasty",
    object == "grade_1" ~ "inferior facetectomies",
    object == "complete_facetectomy" ~ "complete facetectomies",
    object == "grade_2" ~ "posterior column osteotomies",
    object == "grade_3" ~ "pedicle subtraction osteotomy",
    object == "grade_4" ~ "extended pedicle subtraction osteotomy",
    object == "grade_5" ~ "vertebral column resection",
    object == "no_implant_interbody_fusion" ~ "interbody fusion (without interbody implant)",
    object == "llif" ~ "lateral lumbar interbody fusion and insertion of interbody device",
    object == "plif" ~ "posterior lumbar interbody fusion and insertion of interbody device",
    object == "tlif" ~ "transforaminal lumbar interbody fusion and insertion of interbody device"
  )
  procedure_category
}


op_note_number_of_paragraphs_for_procedure_category <- function(procedure_cat){
  paragraph_type <- case_when(
    procedure_cat == 'vertebral cement augmentation' ~ "combine",
    procedure_cat == 'posterior spinal instrumentation' ~ "combine",
    procedure_cat == 'occiput instrumentation' ~ "combine",
    procedure_cat == 'pelvic instrumentation' ~ "combine",
    procedure_cat == 'vertebral body posterior tethering' ~ "combine",
    procedure_cat == 'complete facetectomies' ~ "combine",
    procedure_cat == 'inferior facetectomies' ~ "combine",
    procedure_cat == 'posterior column osteotomies' ~ "combine",
    procedure_cat == 'pedicle subtraction osteotomy' ~ "distinct",
    procedure_cat == 'extended pedicle subtraction osteotomy' ~ "distinct",
    procedure_cat == 'vertebral column resection' ~ "distinct",
    procedure_cat == 'decompression' ~ "combine",
    procedure_cat == 'decompression using a costovertebral approach' ~ "distinct",
    procedure_cat == 'decompression using a transpedicular approach' ~ "distinct",
    procedure_cat == 'revision and reexploration with decompression' ~ "combine",
    procedure_cat == 'revision and reexploration with decompression using a costovertebral approach' ~ "distinct",
    procedure_cat == 'revision and reexploration with decompression using a transpedicular approach' ~ "distinct",
    procedure_cat == 'laminoplasty' ~ "combine",
    procedure_cat == 'lateral lumbar interbody fusion and insertion of interbody device' ~ "distinct",
    procedure_cat == 'transforaminal lumbar interbody fusion and insertion of interbody device' ~ "distinct",
    procedure_cat == 'interbody fusion (without interbody implant)' ~ "distinct",
    procedure_cat == 'posterior lumbar interbody fusion and insertion of interbody device' ~ "distinct"
  )
  paragraph_type
}



# op_note_levels_by_procedure_function <- function(procedure, all_objects_with_procedure_category_df){
#   
#   implant_statements_df <- all_objects_with_procedure_category_df %>%
#     filter(procedure_category == procedure) %>%
#     select(level) %>%
#     distinct()
#   
#   glue_collapse(x = implant_statements_df$level, sep = ", ", last = " and ")
# }


op_note_technique_statement <- function(object, levels_side_df, revision_modifier = "xx"){
  
  revision_statement <- if_else(revision_modifier == "xx", " ", " reexploration and revision decompression with a ")
  
  if(object == "pelvic_screw"){
    pelvic_fixation_method_df <- levels_side_df %>%
      select(level) %>%
      distinct() %>%
      mutate(statement = case_when(
        level == "Iliac" ~ "For iliac screw insertion, the posterior iliac crest was identified and the entry point was countersunk using a rongeur. A probe was used to bore the path of the screw between the two cortices, aimed toward the anterior inferior iliac spine. Once the path was created, the walls of the path were palpated for breaches and the length of the path measured.",
        level == "S2AI" ~ "For S2AI screw insertion, the starting point was identified at the inferior and lateral border of the S1 foramen. A probe was used to bore the path of the screw between the two cortices, across the sacroiliac joint, and aimed toward the anterior inferior iliac spine. Once the path was created, the walls of the path were palpated for breaches and the length of the path measured.",
      ))
    
    pelvic_screws_inserted_df <- levels_side_df %>%
      select(level, side) %>% 
      group_by(level, side) %>%
      add_tally(name = "number_per") %>%
      ungroup() %>%
      distinct() %>%
      mutate(number_statement = if_else(number_per == 1, glue("one {level} screw was placed on the {side} side"), glue("two {level} screws were placed on the {side} side, using slightly cranial and caudal start points."))) 
    
    pelvic_screw_statement <- paste0(as.character(glue_collapse(x = pelvic_fixation_method_df$statement, sep = " ")),
                                     " Using this technique, ", 
                                     as.character(glue_collapse(x = pelvic_screws_inserted_df$number_statement, sep = ", ", last = ", and ")), 
                                     ".")
  }else{
    pelvic_screw_statement <- ""
  }
  
  levels_side_df <- levels_side_df %>%
    group_by(level) %>%
    add_tally(name = "number_per_level") %>%
    mutate(level_side = as.character(if_else(number_per_level == 1, glue("on the {side} at {level}"), glue("on the left and on the right at {level}")))) %>%
    ungroup() %>%
    select(-side) %>%
    distinct()
  
  technique_statement <- case_when(
    object == "cement_augmentation" ~ glue("For vertebral body cement augmentation, a cannula was inserted into the vertebral body through the pedicle. The cement was then injected under x-ray guidance until an appropriate amount of cement had been injected into the vertebral body. Cement augmentation was performed at {glue_collapse(x = levels_side_df$level, sep = ', ', last = ' and ')}."), 
    object == "laminar_downgoing_hook" ~ glue("For downgoing laminar hooks, the ligamentum flavum was removed at the site of the hook insertion. A hook was then inserted securely under the lamina {glue_collapse(x = levels_side_df$level_side, sep = ', ', last = ' and ')}."), 
    object == "laminar_upgoing_hook" ~ glue("For upgoing laminar hooks, the inferior edge of the cranial lamina was identified and the plane between the lamina and ligamentum was developed and the upgoing hook is then placed within this plane, secured to the lamina aimed cranially {glue_collapse(x = levels_side_df$level_side, sep = ', ', last = ' and ')}."), 
    object == "lateral_mass_screw" ~ glue("For lateral mass screw placement, the entry point was identified using the lateral and medial borders of the lateral mass and superior and inferior borders of the facet. The superficial cortex was opened at each entry point using a high speed burr and the screw path drilled incrementally to the far cortex. Lateral mass screws were placed {glue_collapse(x = levels_side_df$level_side, sep = ', ', last = ' and ')}."), 
    object == "occipital_screw" ~ glue("An appropriately sized occipital plate was selected and was placed centered in the midline and just caudal to the external occipital protuberance, but cranial to the foramen magnum. The plate was held in place to identify the appropriate start points for the occipital screws. The occipital screws were drilled incrementally until the anterior cortex was penetrated. The length of the path was measured to acheive bicortical fixation. The screw paths were then tapped and the screws placed, securing the plate to the occiput."), 
    object == "pars_screw" ~ glue("For pars screws, the start point was identified just 3-4mm cranial to the inferior facet joint and in the midpoint of the pars from medial to lateral. Once the start point was identified, the superficial cortex was opened at the entry point using the high speed burr. A drill was used to cannulate a screw path, aiming as dorsal as possible while not perforating the dorsal cortex of the pars. The path was then tapped and the length measured and pars screw placed {glue_collapse(x = levels_side_df$level_side, sep = ', ', last = ' and ')}."), 
    object == "pedicle_screw" ~ glue("For pedicle screws, the transverse process, pars, and superior facet were used as landmarks to identify the appropriate starting point. After identifying the start point, the superficial cortex was opened at each entry point using a high speed burr. A pedicle probe was then used to navigate down the pedicle, followed by palpating a medial, lateral, superior and inferior pedicle wall, measuring, and tapping if appropriate. Pedicle screws were placed {glue_collapse(x = levels_side_df$level_side, sep = ', ', last = ' and ')}."), 
    object == "pedicle_hook" ~ glue("For pedicle hooks, a pedicle finder was carefully placed just under the inferior facet and above the superior facet, until the pedicle was found. Once the pedicle was identified, a pedicle hook was inserted directly toward the inferior pedicle, secured within the residual facet joint {glue_collapse(x = levels_side_df$level_side, sep = ', ', last = ' and ')}."), 
    object == "pelvic_screw" ~ pelvic_screw_statement,
    object == "sublaminar_wire" ~ glue("For sublaminar wiring, the doubled-up sublaminar was was bent into a hook shape and and passed under the inferior lamina from a caudal to cranial direction. Once the wire was safely passed, the tip of the wire was cut and the two strands were directed in opposite directions of the midline to be attached to the rods on the left and right side. Wires were passed under {glue_collapse(x = levels_side_df$level, sep = ', ', last = ' and ')}."), 
    object == "tether" ~ glue("For posterior vertebral tethering, a hole was drilled in the transverse process over the lamina. A band was then thread through the hole and tied in a figure-8 fashion, tethering {glue_collapse(x = levels_side_df$level, sep = ', ', last = ' and ')}."), 
    object == "tp_hook" ~ glue("For transverse process hooks, the cranial edge of the transverse process was identified. A transverse process finder was used to develop the plane and a transverse process hook was placed securely into position along the superior edge of the transverse process."),  
    object == "translaminar_screw" ~ glue("For translaminar screw fixation, the starting point was identified using the spinolaminar junction and in the central plane of the contralateral lamina. A burr hole was made to open the superficial cortex, the path was then cannulated and laminar screws placed {glue_collapse(x = levels_side_df$level_side, sep = ', ', last = ' and ')}."
    ),
    
    object == 'complete_facetectomy' ~ glue("For a complete facetectomy, the inferior, superior, medial and lateral borders of the inferior and superior facet were identified. Both the superior and inferior facet were completely excised and the underlying nerve root decompression. I performed a complete facetectomy {glue_collapse(x = levels_side_df$level_side, sep = ', ', last = ' and ')} and the bone was morselized to be used as morselized autograft."),
    object == 'grade_1' ~ glue("The inferior, superior, medial and lateral borders of the inferior facet were identified. The inferior facets {glue_collapse(x = levels_side_df$level_side, sep = ', ', last = ' and ')} were excised and the bone was morselized to be used as morselized autograft."),
    
    object == 'grade_2' ~ glue("For the posterior column osteotomies, a small rent was made in the interlaminar space to develop the plane between the ligamentum and the dura. A Kerrison rongeur was then used to excise the ligamentum. this was carried out laterally in both directions until the facets were encountered. The superior and inferior facet were both adequately resected to fully release the posterior column. I performed posterior column (Smith-Peterson) osteotomies at {glue_collapse(x = levels_side_df$level, sep = ', ', last = ' and ')}"),
    
    object == 'diskectomy' ~ glue("For a diskectomy, I used the cranial and caudal laminar edges, pars, and facet joints as landmarks. I performed a diskectomy with partial medial facetectomy and foraminotomy {glue_collapse(x = levels_side_df$level_side, sep = ', ', last = ' and ')} interspace to fully decompress the nerve root. Using a high-speed burr and Kerrison rongeurs, I first performed a foraminotomy and excised the ligamentum flavum. The dural sac was identified and traversing root was protected. The annulus was then incised and the diseased disk materal was removed. Following the decompression, the canal and foramen and lateral recess were palpated to confirm an adequate decompression had been completed."),
    
    object == 'laminotomy' ~ glue("For the laminotomy, the cranial and caudal laminar edges, pars, and facet joints were used as landmarks. Once I had determined the laminotomy site, I used a combination of a high-speed burr and Kerrison rongeurs to resect the bone dorsal to the nerve root. I performed a laminotomy {glue_collapse(x = levels_side_df$level_side, sep = ', ', last = ' and ')} interspace to fully decompress the nerve root. Following the decompression, the foramen was palpated to confirm an adequate decompression had been completed."),
    
    object == 'laminectomy' ~ glue("Using the cranial and caudal edges of the lamina and pars as landmarks, I performed a laminectomy at {glue_collapse(x = levels_side_df$level, sep = ', ', last = ' and ')}. First, using a combination of a high-speed burr and Kerrison rongeurs, I resected the dorsal lamina. I then excised the underlying ligamentum flavum. Following the decompression, the canal was palpated to confirm an adequate decompression had been completed."),
    
    object == 'sublaminar_decompression' ~ glue("Using a combination of a high-speed burr and Kerrison rongeurs, I performed a sublaminar decompression bilaterally at the {glue_collapse(x = levels_side_df$level, sep = ', ', last = ' and ')} interspace. First, I performed partial laminectomies and excised the ligamentum flavum, exposing the dura. The medial facet was partially excised and a foraminotomy performed on the left and right at the {glue_collapse(x = levels_side_df$level, sep = ', ', last = ' and ')} interspace, to fully decompress the exiting and traversing nerve roots within the neural foramen and lateral recess. Following the decompression, the canal and foramen were palpated to confirm an adequate decompression had been completed."),
    
    object == 'revision_diskectomy' ~ glue("For the revision diskectomy, I used the cranial and caudal laminar edges, pars, and facet joints as landmarks. I performed a revision and reexploration with diskectomy and partial medial facetectomy and foraminotomy {glue_collapse(x = levels_side_df$level_side, sep = ', ', last = ' and ')} interspace to fully decompress the nerve root. I carefully dissected off the scar until I was able to safely identify the bony edges and develop a plane between the dura and scar. Using a high-speed burr and Kerrison rongeurs, I performed a foraminotomy and excised the scar and ligamentum. The dural sac was identified and traversing root was protected. The annulus and disk space were identified and the diseased disk material was excised. Following the revision decompression, the canal and foramen and lateral recess were palpated to confirm an adequate decompression had been completed."),
    
    object == 'revision_laminotomy' ~ glue("For the revision laminotomy, the cranial and caudal laminar edges, pars, and facet joints were used as landmarks. I carefully exposed the dorsal elements until I had identified the edges of the laminar defect. Once I determined the laminotomy site, I used a combination of a high-speed burr and Kerrison rongeurs to resect the bone dorsal to the nerve root. I performed a revision laminotomy {glue_collapse(x = levels_side_df$level_side, sep = ', ', last = ' and ')} interspace to fully decompress the nerve root. Following the decompression, the foramen was palpated to confirm an adequate decompression had been completed."),
   
    object == 'revision_laminectomy' ~ glue("Using the cranial and caudal edges of the lamina and pars as landmarks, I performed a reexploration and revision laminectomy at {glue_collapse(x = levels_side_df$level, sep = ', ', last = ' and ')}. Using a combination of a high-speed burr, currettes and Kerrison rongeurs, I carefully dissected off the scar until I was able to safely identify the bony edges and develop a plane between the dura and scar. I removed any dorsal lamina, ligamentum flavum and scar thought to still be causing compression. The central canal was palpated to confirm full decompression of the thecal sac. Following the revision decompression, the canal was palpated to confirm an adequate decompression had been completed."),
    
    object == 'revision_sublaminar_decompression' ~ glue("Using a combination of a high-speed burr and Kerrison rongeurs, I performed a reexploration and revision sublaminar decompression bilaterally at the {glue_collapse(x = levels_side_df$level, sep = ', ', last = ' and ')} interspace. First, I carefully dissected off the scar until I was able to safely identify the bony edges and develop a plane between the dura and scar. I proceeded with partial laminectomies and excised the scar and underlyingligamentum flavum. The medial facet was partially excised and a foraminotomy performed on the left and right at the {glue_collapse(x = levels_side_df$level, sep = ', ', last = ' and ')} interspace, to fully decompress the exiting and traversing nerve roots within the neural foramen and lateral recess. Following the revision decompression, the canal and foramen were palpated to confirm an adequate decompression had been completed."),
    
    object == 'laminoplasty' ~ glue("For laminoplasty, an opening and hinge trough was created with a high-speed burr angled perpendicular to the lamina at the lateral mass-lamina junction. This was performed at {glue_collapse(x = levels_side_df$level, sep = ', ', last = ' and ')}. After all troughs were completed, greenstick fractures were created to open the lamina at the laminoplasty levels, the ligamentum flavum at the proximal and distal levels was excised, and laminoplasty plates were sequentially secured into place. The spinous processes were trimmed and the canal was palpated to confirm an adequate decompression had been completed.")
  )
  technique_statement
}



op_note_distinct_technique_statement <- function(object, level, side, revision_modifier = "xx"){
  
  revision_statement <- if_else(revision_modifier == "xx", "", "reexploration and revision decompression with a")
  
  
  
  technique_statement <- case_when(
    object == 'transpedicular_approach' ~ glue("I then proceeded with a transpedicular approach for decompression from the {side} at {level}. Using a combination of a high-speed burr and Kerrison rongeurs, the posterior elements were resected and the {side} {level} pedicle was skeletonized and resected, to allow full decompression of the {if_else(str_starts(level, 'L'), 'cauda equina and nerve roots', 'spinal cord')} at the {level} level. Following the decompression, the canal was palpated to confirm an adequate decompression had been completed. This completed the decompression through a transpedicular approach at {level}."),
    object == 'costovertebral_approach' ~ glue("I then proceeded with a costovertebral approach for decompression from the {side} at {level}. The {side} {level} rib was identified, skeletonized, and an adequate amount of the rib was resected to allow access to the dorsal vertebral body. Using a combination of a high-speed burr and Kerrison rongeurs, the posterior elements were resected and the {side} {level} pedicle was skeletonized and resected, to allow full decompression of the spinal cord at the {level} level. Following the decompression, the canal was palpated to confirm an adequate decompression had been completed. This completed the decompression through a costovertebral approach at {level}."),
    object == 'revision_transpedicular_approach' ~ glue("I then proceeded with a transpedicular approach for a reexploration and revision decompression from the {side} at {level}. Using a combination of a high-speed burr, currettes, and Kerrison rongeurs, the scar and posterior elements were carefully resected until I found the plane between scar and dura. The {side} {level} pedicle was skeletonized and resected, to allow full decompression of the {if_else(str_starts(level, 'L'), 'cauda equina and nerve roots', 'spinal cord')} at the {level} level. Following the revision decompression, the canal was palpated to confirm an adequate decompression had been completed. This completed the reexploration and revision decompression through a transpedicular approach at {level}."),
    object == 'revision_costovertebral_approach' ~ glue("I then proceeded with a costovertebral approach for a reexploration and revision decompression from the {side} at {level}. The {side} {level} rib was identified, skeletonized, and an adequate amount of the rib was resected to allow access to the dorsal vertebral body. Using a combination of a high-speed burr, currettes, and Kerrison rongeurs, the scar and posterior elements were carefully resected until I found the plane between scar and dura. The {side} {level} pedicle was skeletonized and resected, to allow full decompression of the spinal cord at the {level} level. Following the revision decompression, the canal was palpated to confirm an adequate decompression had been completed. This completed the reexploration and revision decompression through a costovertebral approach at {level}."),
    object == 'grade_3' ~ glue("I then proceeded with the pedicle subtraction osteotomy at the level of {level}. The posterior elements of {level} were completely removed. A central laminectomy was performed at the cranial level in order to prevent compression after osteotomy closure. Both pedicles were skeletonized at {level} and the cranial and caudal nerve roots were identified and fully decompressed from pedicle to pedicle. Once the dorsal decompression was complete, we began the osteotomy. A subperiosteal plane was developed around the anterior portion of the {level} body and retractors were held in place to protect the retroperiteal structures. The dura, cranial and caudal nerve roots were protected. A high speed burr was used to bore out the pedicle and develop a defect in the vertebral body at the level of the pedicle. The lateral portion of the pedicle wall was taken down, allowing easier access to the vertebral body and the vertebral body was hollowed out, taking care to not perforate the anterior cortex and the pedicle wall was excised. We then placed a temporary rod and repeated the same process on the contralateral pedicle. Once an adequate defect had been generated in the vertebral body, the dorsal wall of the vertebral body was excised, the osteotomy was closed, and the other rod was placed into position and set screws final tightened. Intraoperative xray was performed to confirm adequate lordosis. This completed the pedicle subtraction osteotomy at the {level} level."),
    object == 'grade_4' ~ glue("I then proceeded with an extended three column osteotomy (partial corpectomy) at the level of {level}. The posterior elements of {level} were completely removed. A central laminectomy was performed at the cranial level in order to prevent compression after osteotomy closure. Both pedicles were skeletonized at {level} and the cranial and caudal nerve roots were identified and fully decompressed from pedicle to pedicle. Once the dorsal decompression was complete, we began the osteotomy. A subperiosteal plane was developed around the anterior portion of the {level} body and retractors were held in place to protect the retroperiteal structures. The dura, cranial and caudal nerve roots were protected. A high speed burr was used to bore out the pedicle and develop a defect in the vertebral body at the level of the pedicle and extending into the cranial disk space. The lateral portion of the pedicle wall was taken down, allowing easier access to the vertebral body and the vertebral body was hollowed out, taking care to not perforate the anterior cortex and the pedicle wall was excised. We then placed a temporary rod and repeated the same process on the contralateral pedicle. Once an adequate defect (over 50%) had been generated in the vertebral body, the dorsal wall of the vertebral body was excised, the osteotomy was closed, and the other rod was placed into position and set screws final tightened. Intraoperative xray was performed to confirm adequate lordosis. This completed the extended three column osteotomy/partial corpectomy at the {level} level."),
    object == 'grade_5' ~ glue("I then proceeded with a vertebral column resection at the level of {level}. The posterior elements of {level} were completely removed. A central laminectomy was performed at the cranial level in order to prevent compression after osteotomy closure. Both pedicles were skeletonized at {level} and the cranial and caudal nerve roots were identified and fully decompressed from pedicle to pedicle. Once the dorsal decompression was complete, we began the vertebral resection. A subperiosteal plane was developed around the anterior portion of the {level} body and retractors were held in place to protect the retroperiteal structures. The dura, cranial and caudal nerve roots were protected. A high speed burr was used to bore out the pedicle and develop a defect in the vertebral body at the level of the pedicle and extending into the cranial disk space. The lateral portion of the pedicle wall was taken down, allowing easier access to the vertebral body and the vertebral body was hollowed out, using both pedicles to access the body. We then placed a temporary rod. Retractors were held in place and the remaining portion of the entire vertebral body was removed. The other rod was placed into position and the deformity was corrected. Intraoperative xray was performed to confirm adequate alignment. This completed the vertebral column resection at the {level} level."),
    object == 'no_implant_interbody_fusion' ~ glue("I then proceeded with the interbody fusion from the {side} side at the level of {level}. The inferior and superior facets of {str_replace_all(level, '-', ' and ')}, respectively, were resected and the exiting and traversing nerve roots were appropriately protected. The annulus was incised, allowing access to the disk space. The disk was excised and endplates were prepped using a combination of currettes, shavers, and pituitary rongeurs. Once the endplates were adequately prepped, the size was confirmed and the interbody implant was placed into position along with allograft. The final position was confirmed using intraoperative xray."),
    object == 'plif' ~ glue("I then proceeded with the posterior lumbar interbody fusion (PLIF) procedure and placement of interbody implant at the level of {level}. The inferior and superior facets of {str_replace_all(level, '-', ' and ')}, respectively, were partially resected and the exiting and traversing nerve roots were appropriately protected. The dura was retracted in order to access the disc space. The annulus was incised, allowing access to the disk space. The disk was excised and endplates were prepped using a combination of currettes, shavers, and pituitary rongeurs. Once the endplates were adequately prepped, trials were used to determine the appropriate size of the implant. Once I was satisfied with the size and fit of the trial, the interbody implant was placed into the interbody space along with allograft bone. The final position of the implant was confirmed using intraoperative xray."),
    object == "tlif" ~ glue("I then proceeded with the transforaminal interbody fusion (TLIF) procedure and placement of interbody implant from the {side} side at the level of {level}. The inferior and superior facets of {str_replace_all(level, '-', ' and ')}, respectively, were resected and the exiting and traversing nerve roots were appropriately protected. The annulus was incised, allowing access to the disk space. The disk was excised and endplates were prepped using a combination of currettes, shavers, and pituitary rongeurs. Once the endplates were adequately prepped, trials were used to determine the appropriate size of the implant. Once I was satisfied with the size and fit of the trial, the interbody implant was placed into the interbody space along with allograft bone. The final position of the implant was confirmed using intraoperative xray.")
  )
  
  technique_statement
}

create_full_paragraph_statement_function <- function(procedure_paragraph_intro, df_with_levels_object_nested, paragraphs_combined_or_distinct){
  if(paragraphs_combined_or_distinct == "combine"){
    
    df_with_statement <- df_with_levels_object_nested %>%
      group_by(object) %>%
      nest() %>%
      mutate(object_levels_side_df = data) %>%
      select(-data) %>%
      mutate(tech_statement = map2(.x = object, .y = object_levels_side_df, .f = ~ op_note_technique_statement(object = .x, levels_side_df = .y))) %>%
      select(object, tech_statement) %>%
      unnest() %>%
      distinct()
    
    # df_with_statement <-df_with_levels_object_nested %>%
    #   mutate(revision_levels_vector = list(revision_decompression_vector)) %>%
    #   mutate(revision_level = map2(.x = level, .y = revision_levels_vector, .f = ~ str_detect(string = .x, pattern = .y))) %>%
    #   select(-revision_levels_vector) %>%
    #   mutate(revision_level = map(.x = revision_level, .f = ~ any(.x))) %>%
    #   unnest() %>%
    #   mutate(object = if_else(revision_level == TRUE, paste("revision", object, sep = "_"), object)) %>%
    #   group_by(object) %>%
    #   nest() %>%
    #   mutate(object_levels_side_df = data) %>%
    #   select(-data) %>%
    #   mutate(tech_statement = map2(.x = object, .y = object_levels_side_df, .f = ~ op_note_technique_statement(object = .x, levels_side_df = .y))) %>%
    #   select(object, tech_statement) %>%
    #   unnest() %>%
    #   distinct()
        
    
    df_levels <- df_with_levels_object_nested %>%
      select(level, vertebral_number) %>%
      distinct() %>%
      arrange(vertebral_number)
    
    
    if(procedure_paragraph_intro == "pelvic instrumentation" | procedure_paragraph_intro == "posterior spinal instrumentation"){
      if(procedure_paragraph_intro == "pelvic instrumentation"){
        statement <- glue("I then proceeded with instrumentation of the pelvis. {glue_collapse(df_with_statement$tech_statement, sep = ' ')} This completed the instrumentation of the pelvis.")
      }
      if(procedure_paragraph_intro == "posterior spinal instrumentation"){
        statement <- glue("I then proceeded with the posterior spinal instrumentation. {glue_collapse(df_with_statement$tech_statement, sep = ' ')} This partially completed the {procedure_paragraph_intro} of {glue_collapse(unique(x = df_levels$level), sep = ', ', last = ', and ')}.")
      }
      
    }else{
      statement <- glue("I then proceeded with the {procedure_paragraph_intro}. {glue_collapse(df_with_statement$tech_statement, sep = ' ')} This completed the {procedure_paragraph_intro} of {glue_collapse(unique(x = df_levels$level), sep = ', ', last = ', and ')}.")
    }
    
  }
  
  if(paragraphs_combined_or_distinct == "distinct"){
    df_with_statement <- df_with_levels_object_nested %>%
      mutate(tech_statement_detail = pmap(.l = list(..1 = object, 
                                                    ..2 = level, 
                                                    ..3 = side),
                                          .f = ~op_note_distinct_technique_statement(object = ..1, level = ..2, side = ..3))) %>% 
      select(object, level, object, tech_statement_detail) %>%
      unnest() %>%
      mutate(procedure_category = op_note_procedure_category_function(object = object)) %>%
      mutate(tech_statement = paste(tech_statement_detail, glue("This completed the {procedure_category} at the {level} {if_else(str_detect(level, '-'), 'interspace', 'level')}.")))
    
    statement <- glue_collapse(df_with_statement$tech_statement, sep = "\n\n")
  }
  
  return(statement)
  
}

op_note_procedure_paragraphs_function <- function(objects_added_df, revision_decompression_vector = NULL){
  df_for_paragraphs <- objects_added_df %>%
    mutate(revision_levels_vector = list(revision_decompression_vector)) %>%
    select(level, vertebral_number, approach, category, object, side, revision_levels_vector) %>%
    mutate(revision_level = map2(.x = level, .y = revision_levels_vector, .f = ~ str_detect(string = .x, pattern = .y))) %>%
    select(-revision_levels_vector) %>%
    mutate(revision_level = map(.x = revision_level, .f = ~ any(.x))) %>%
    unnest() %>%
    mutate(object = if_else(category == "decompression" & revision_level == TRUE, paste0("revision_", object), object)) %>%
    mutate(procedure_category = op_note_procedure_category_function(object = object)) %>%
    select(level, vertebral_number, procedure_category, object, side) %>%
    mutate(procedures_combine = op_note_number_of_paragraphs_for_procedure_category(procedure_cat = procedure_category)) %>%
    group_by(procedure_category, procedures_combine, object) %>%
    nest() %>%
    ungroup() %>%
    group_by(procedure_category, procedures_combine) %>%
    nest() %>%
    mutate(nested_data = map(.x = data, .f = ~ unnest(.x))) %>%
    select(-data)
  
  
  procedures_op_full_df <- df_for_paragraphs %>%
    mutate(procedure_statement = pmap(list(..1 = procedure_category,
                                           ..2 = nested_data, 
                                           ..3 = procedures_combine),
                                      .f = ~create_full_paragraph_statement_function(procedure_paragraph_intro = ..1,
                                                                                     df_with_levels_object_nested = ..2, 
                                                                                     paragraphs_combined_or_distinct = ..3))) %>%
    select(procedure_category, procedures_combine, procedure_statement) %>%
    unnest()
  
  glue_collapse(x = procedures_op_full_df$procedure_statement, sep = "\n\n")
  
}




```

## testing
```{r}
test_revision_decompression_vector <- c("L3")

lumbar_test_df %>%
      mutate(revision_levels_vector = list(test_revision_decompression_vector)) %>%
  select(level, vertebral_number, approach, category, object, side, revision_levels_vector) %>%
      mutate(revision_level = map2(.x = level, .y = revision_levels_vector, .f = ~ str_detect(string = .x, pattern = .y))) %>%
      select(-revision_levels_vector) %>%
      mutate(revision_level = map(.x = revision_level, .f = ~ any(.x))) %>%
      unnest() %>%
  mutate(object = if_else(category == "decompression" & revision_level == TRUE, paste0("revision_", object), object)) %>%
  mutate(procedure_category = op_note_procedure_category_function(object = object))

all_implants_constructed_df %>%
  mutate(procedure_category = op_note_procedure_category_function(object = object)) %>%
  select(level, vertebral_number, approach, procedure_category, category, object, side) %>%
  tabyl(procedure_category, category)


test_op <- op_note_procedure_paragraphs_function(objects_added_df = lumbar_test_df, revision_decompression_vector = c("L3"))

test_op

```
### testing procedures performed summary
```{r}
op_note_procedure_performed_summary_classifier_function <- function(object){
  procedure_category <- case_when(
    object == "cement_augmentation" ~ "Vertebral cement augmentation",
    object == "laminar_downgoing_hook" ~ "Posterior spinal instrumentation",
    object == "laminar_upgoing_hook" ~ "Posterior spinal instrumentation",
    object == "lateral_mass_screw" ~ "Posterior spinal instrumentation",
    object == "occipital_screw" ~ "Occiput instrumentation",
    object == "pars_screw" ~ "Posterior spinal instrumentation",
    object == "pedicle_hook" ~ "Posterior spinal instrumentation",
    object == "pedicle_screw" ~ "Posterior spinal instrumentation",
    object == "laminar_downgoing_hook" ~ "Posterior spinal instrumentation",
    object == "sublaminar_wire" ~ "Posterior spinal instrumentation",
    object == "tp_hook" ~ "Posterior spinal instrumentation",
    object == "translaminar_screw" ~ "Posterior spinal instrumentation",
    object == "pelvic_screw" ~ "Pelvic instrumentation",
    object == "tether" ~ "Vertebral body Posterior tethering",
    object == "costovertebral_approach" ~ "Decompression using a costovertebral approach",
    object == "revision_costovertebral_approach" ~ "Reexploration and revision decompression using a costovertebral approach",
    object == "transpedicular_approach" ~ "Decompression using a transpedicular approach",
    object == "revision_transpedicular_approach" ~ "Reexploration and revision decompression using a transpedicular approach",
    object == "diskectomy" ~ "Decompression with diskectomy and laminotomy",
    object == "sublaminar_decompression" ~ "Decompression with bilateral partial laminectomies, foraminotomies, and medial facetectomies",
    object == "laminectomy" ~ "Decompression with central laminectomy",
    object == "laminotomy" ~  "Decompression with laminotomy and medial facetectomy",
    object == "revision_diskectomy" ~ "Reexploration and revision decompression with diskectomy and laminotomy",
    object == "revision_sublaminar_decompression" ~ "Reexploration and revision decompression with bilateral partial laminectomies, foraminotomies, and medial facetectomies",
    object == "revision_laminectomy" ~ "Reexploration and revision decompression with central laminectomy",
    object == "revision_laminotomy" ~ "Reexploration and revision decompression with laminotomy and medial facetectomy",
    object == "laminoplasty" ~ "Laminoplasty",
    object == "grade_1" ~ "Inferior facetectomies",
    object == "complete_facetectomy" ~ "Complete facetectomy",
    object == "grade_2" ~ "Posterior column osteotomy",
    object == "grade_3" ~ "Pedicle subtraction osteotomy",
    object == "grade_4" ~ "Extended three column osteotomy (vertebral body partial corpectomy)",
    object == "grade_5" ~ "Vertebral column resection",
    object == "no_implant_interbody_fusion" ~ "Interbody fusion (without interbody implant)",
    object == "llif" ~ "Lateral lumbar interbody fusion and insertion of interbody device",
    object == "plif" ~ "Posterior lumbar interbody fusion and insertion of interbody device",
    object == "tlif" ~ "Transforaminal lumbar interbody fusion and insertion of interbody device"
  )
  procedure_category
}

op_note_procedure_performed_summary_per_line_function <- function(procedure_type){
  procedures_per_line <- case_when(
    procedure_type == 'Vertebral cement augmentation' ~ 'multiple',
    procedure_type == 'Posterior spinal instrumentation' ~ 'multiple',
    procedure_type == 'Occiput instrumentation' ~ 'multiple',
    procedure_type == 'Pelvic instrumentation' ~ 'multiple',
    procedure_type == 'Vertebral body Posterior tethering' ~ 'multiple',
    procedure_type == 'Complete facetectomy' ~ 'multiple',
    procedure_type == 'Inferior facetectomies' ~ 'multiple',
    procedure_type == 'Posterior column osteotomy' ~ 'multiple',
    procedure_type == 'Pedicle subtraction osteotomy' ~ 'one',
    procedure_type == 'Extended three column osteotomy (vertebral body partial corpectomy)' ~ 'one',
    procedure_type == 'Vertebral column resection' ~ 'one',
    procedure_type == 'Decompression with diskectomy and laminotomy' ~ 'multiple',
    procedure_type == 'Decompression with laminotomy and medial facetectomy' ~ 'multiple',
    procedure_type == 'Decompression with central laminectomy' ~ 'multiple',
    procedure_type == 'Decompression with bilateral partial laminectomies, foraminotomies, and medial facetectomies' ~ 'multiple',
    procedure_type == "Reexploration and revision decompression with diskectomy and laminotomy" ~ 'multiple',
    procedure_type == "Reexploration and revision decompression with bilateral partial laminectomies, foraminotomies, and medial facetectomies" ~ 'multiple',
    procedure_type == "Reexploration and revision decompression with central laminectomy" ~ 'multiple',
    procedure_type == "Reexploration and revision decompression with laminotomy and medial facetectomy"~ 'multiple',
    procedure_type == 'Laminoplasty' ~ 'multiple',
    procedure_type == 'Decompression using a transpedicular approach' ~ 'one',
    procedure_type == 'Decompression using a costovertebral approach' ~ 'one',
    procedure_type == 'Reexploration and revision decompression using a transpedicular approach' ~ 'one',
    procedure_type == 'Reexploration and revision decompression using a costovertebral approach' ~ 'one',
    procedure_type == 'Interbody fusion (without interbody implant)' ~ 'one',
    procedure_type == 'Lateral lumbar interbody fusion and insertion of interbody device' ~ 'one',
    procedure_type == 'Transforaminal lumbar interbody fusion and insertion of interbody device' ~ 'one',
    procedure_type == 'Interbody fusion (without interbody implant)' ~ 'one',
    procedure_type == 'Posterior lumbar interbody fusion and insertion of interbody device' ~ 'one',
  )
  procedures_per_line
}

extract_levels_function <- function(input_df){
  levels_df <- input_df %>%
    arrange(vertebral_number) %>%
    select(level) %>%
    distinct()
  
  glue_collapse(x = levels_df$level, sep = ", ", last = " and ")
  
}


op_note_procedures_performed_numbered_function <- function(objects_added_df, revision_decompression_vector = NULL){
  summary_nested_df <- objects_added_df %>%
    mutate(revision_levels_vector = list(revision_decompression_vector)) %>%
    select(level, vertebral_number, approach, category, object, side, revision_levels_vector) %>%
    mutate(revision_level = map2(.x = level, .y = revision_levels_vector, .f = ~ str_detect(string = .x, pattern = .y))) %>%
    select(-revision_levels_vector) %>%
    mutate(revision_level = map(.x = revision_level, .f = ~ any(.x))) %>%
    unnest() %>%
    mutate(object = if_else(category == "decompression" & revision_level == TRUE, paste0("revision_", object), object)) %>%
    select(level, object, vertebral_number) %>%
    mutate(procedure_class = op_note_procedure_performed_summary_classifier_function(object = object)) %>%
    mutate(procedures_per_line = op_note_procedure_performed_summary_per_line_function(procedure_type = procedure_class)) 
    
  summary_single_statements <- summary_nested_df %>%
    filter(procedures_per_line == "one") %>%
    mutate(procedure_performed_statement = glue("{procedure_class} at {level}"))%>%
    select(procedure_class, procedure_performed_statement)
  
  summary_multiple_nested <- summary_nested_df %>%
    filter(procedures_per_line == "multiple") %>%
    group_by(procedure_class) %>%
    nest() %>%
    ungroup() %>%
    mutate(count = row_number()) %>%
    mutate(levels = map(.x = data, .f = ~ extract_levels_function(input_df = .x))) %>%
    select(-data) %>%
    unnest() %>%
    mutate(procedure_performed_statement = glue("{procedure_class} at {levels}")) %>%
    mutate(procedure_performed_statement = if_else(procedure_class == "Pelvic instrumentation", paste("Instrumentation of the Pelvis with", levels, "fixation"), as.character(procedure_performed_statement))) %>%
    select(procedure_class, procedure_performed_statement)
  
  procedures_numbered_df <- summary_nested_df %>%
    select(procedure_class) %>%
    distinct() %>%
    left_join(summary_single_statements %>%
                union_all(summary_multiple_nested)) %>%
    mutate(count = row_number()) %>%
    mutate(procedures_performed_numbered = glue("{count}. {procedure_performed_statement}")) %>%
    select(procedures_performed_numbered)
  
  glue_collapse(procedures_numbered_df$procedures_performed_numbered, sep = "\n")
}



op_note_procedures_performed_numbered_function(objects_added_df = lumbar_test_df, revision_decompression_vector = c("L3"))




```


```{r}
summary_test_nested_df <- lumbar_test_df %>%
  select(level, object, vertebral_number) %>%
  mutate(procedure_class = op_note_procedure_performed_summary_classifier_function(object = object)) %>%
  mutate(procedures_per_line = op_note_procedure_performed_summary_per_line_function(procedure_type = procedure_class)) 


summary_test_single_statements <- summary_test_nested_df %>%
  filter(procedures_per_line == "one") %>%
  mutate(procedure_performed_statement = glue("{procedure_class} at {level}"))%>%
  select(procedure_class, procedure_performed_statement)


summary_test_multiple_nested <- summary_test_nested_df %>%
  filter(procedures_per_line == "multiple") %>%
  group_by(procedure_class) %>%
  nest() %>%
    ungroup() %>%
  mutate(count = row_number())



summary_test_multiple_statements_df <- summary_test_multiple_nested %>%
  mutate(levels = map(.x = data, .f = ~ extract_levels_function(input_df = .x))) %>%
  select(-data) %>%
  unnest() %>%
  mutate(procedure_performed_statement = glue("{procedure_class} at {levels}")) %>%
  mutate(procedure_performed_statement = if_else(procedure_class == "Pelvic instrumentation", paste("Instrumentation of the Pelvis with", levels, "fixation"), as.character(procedure_performed_statement))) %>%
  select(procedure_class, procedure_performed_statement)


procedures_numbered_df <- summary_test_nested_df %>%
  select(procedure_class) %>%
  distinct() %>%
  left_join(summary_test_single_statements %>%
  union_all(summary_test_multiple_statements_df)) %>%
  mutate(count = row_number()) %>%
  mutate(procedures_performed_numbered = glue("{count}. {procedure_performed_statement}")) %>%
  select(procedures_performed_numbered)



glue_collapse(procedures_numbered_df$procedures_performed_numbered, sep = "\n")


  


```


```{r}
op_note_procedures_performed_summary_function <- function(objects_added_df, revision_decompression_vector = NULL){
  df_for_paragraphs <- objects_added_df %>%
    mutate(revision_levels_vector = list(revision_decompression_vector)) %>%
    select(level, vertebral_number, approach, category, object, side, revision_levels_vector) %>%
    mutate(revision_level = map2(.x = level, .y = revision_levels_vector, .f = ~ str_detect(string = .x, pattern = .y))) %>%
    select(-revision_levels_vector) %>%
    mutate(revision_level = map(.x = revision_level, .f = ~ any(.x))) %>%
    unnest() %>%
    mutate(object = if_else(category == "decompression" & revision_level == TRUE, paste0("revision_", object), object)) %>%
    mutate(procedure_category = op_note_procedure_category_function(object = object)) %>%
    select(level, vertebral_number, procedure_category, object, side) %>%
    mutate(procedures_combine = op_note_number_of_paragraphs_for_procedure_category(procedure_cat = procedure_category)) %>%
    group_by(procedure_category, procedures_combine, object) %>%
    nest() %>%
    ungroup() %>%
    group_by(procedure_category, procedures_combine) %>%
    nest() %>%
    mutate(nested_data = map(.x = data, .f = ~ unnest(.x))) %>%
    select(-data)
  
  df_for_paragraphs
  
  # 
  # procedures_op_full_df <- df_for_paragraphs %>%
  #   mutate(procedure_statement = pmap(list(..1 = procedure_category,
  #                                          ..2 = nested_data, 
  #                                          ..3 = procedures_combine),
  #                                     .f = ~create_full_paragraph_statement_function(procedure_paragraph_intro = ..1,
  #                                                                                    df_with_levels_object_nested = ..2, 
  #                                                                                    paragraphs_combined_or_distinct = ..3))) %>%
  #   select(procedure_category, procedures_combine, procedure_statement) %>%
  #   unnest()
  # 
  # glue_collapse(x = procedures_op_full_df$procedure_statement, sep = "\n\n")
  
}

lumbar_test_df


nested_df <- op_note_procedures_performed_summary_function(objects_added_df = lumbar_test_df, revision_decompression_vector = c("L3")) %>%
  ungroup() %>%
  mutate(order_of_procedures = row_number())

nested_df$nested_data[[2]]

combined_proc_summary_df <- nested_df %>%
  
  mutate(statement = glue("{str_to_title(procedure_category)} at {glue_collapse(data[[row_number()]]$level, sep = ', ', last = ' and ')}"))

combined_proc_summary_df <- lumbar_test_df %>%
  filter(approach == "posterior") %>%
  mutate(procedure_category = op_note_procedure_category_function(object = object)) %>%
  select(level, vertebral_number, procedure_category, object, side) %>%
  mutate(procedures_combine = op_note_number_of_paragraphs_for_procedure_category(procedure_cat = procedure_category)) %>%
  filter(procedures_combine == "combine") %>%
    select(procedure_category, level, side) %>%
  group_by(procedure_category) %>%
  nest() %>%
  # ungroup() %>%
  # mutate(count = row_number()) %>%
  mutate(statement = glue("{str_to_title(procedure_category)} at {glue_collapse(data[[row_number()]]$level, sep = ', ', last = ' and ')}")) %>%
  ungroup() %>%
  mutate(statement = as.character(glue("{row_number()}. {statement}"))) 

distinct_proc_summary_df <- lumbar_test_df %>%
  filter(approach == "posterior") %>%
  mutate(procedure_category = op_note_procedure_category_function(object = object)) %>%
  select(level, vertebral_number, procedure_category, object, side) %>%
  mutate(procedures_combine = op_note_number_of_paragraphs_for_procedure_category(procedure_cat = procedure_category)) %>%
  filter(procedures_combine == "distinct") %>%
    select(procedure_category, level, side) %>%
mutate(statement = glue("{row_number()}. {str_to_title(procedure_category)} at {level}")) 


summary_test_nested_df <- lumbar_test_df %>%
  select(level, object, vertebral_number) %>%
  mutate(procedure_class = op_note_procedure_performed_summary_classifier_function(object = object)) %>%
  group_by(procedure_class) %>%
  print()
  nest()

summary_test_nested_df

summary_test_nested_df


summary_test_nested_df$data[[2]]


```





```{r}
test_df_for_pargraphs <- lumbar_test_df %>%
  mutate(procedure_category = op_note_procedure_category_function(object = object)) %>%
  select(level, vertebral_number, procedure_category, object, side) %>%
  mutate(procedures_combine = op_note_number_of_paragraphs_for_procedure_category(procedure_cat = procedure_category)) %>%
  group_by(procedure_category, procedures_combine, object) %>%
  nest() %>%
  ungroup() %>%
  group_by(procedure_category, procedures_combine) %>%
  nest() %>%
  mutate(nested_data = map(.x = data, .f = ~ unnest(.x))) %>%
  select(-data)

lumbar_test_df %>%
    # filter(approach == "posterior") %>%
    mutate(procedure_category = op_note_procedure_category_function(object = object)) %>%
    select(level, vertebral_number, procedure_category, object, side) %>%
    mutate(procedures_combine = op_note_number_of_paragraphs_for_procedure_category(procedure_cat = procedure_category)) %>%
    group_by(procedure_category, procedures_combine, object) %>%
  print()
    nest() %>%
    ungroup() %>%
    group_by(procedure_category, procedures_combine) %>%
    nest() %>%
    mutate(nested_data = map(.x = data, .f = ~ unnest(.x))) %>%
    select(-data)

test_df_for_pargraphs
test_revision_decompression_vector <- c("L3")

test_df_for_pargraphs$nested_data[[2]] %>%
      mutate(revision_levels_vector = list(test_revision_decompression_vector)) %>%
      mutate(revision_level = map2(.x = level, .y = revision_levels_vector, .f = ~ str_detect(string = .x, pattern = .y))) %>%
      select(-revision_levels_vector) %>%
      mutate(revision_level = map(.x = revision_level, .f = ~ any(.x))) %>%
      unnest() %>%
      mutate(object = if_else(revision_level == TRUE, paste("revision", object, sep = "_"), object)) %>%
      group_by(object) %>%
      nest() %>%
      mutate(object_levels_side_df = data) %>%
      select(-data) %>%
      mutate(tech_statement = map2(.x = object, .y = object_levels_side_df, .f = ~ op_note_technique_statement(object = .x, levels_side_df = .y))) %>%
      select(object, tech_statement) %>%
      unnest() %>%
      distinct()

test_df_for_pargraphs$nested_data[[3]] %>%
  mutate(revision_levels_vector = list(revision_decompression_test_df$level)) %>%
  mutate(revision_level = map2(.x = level, .y = revision_levels_vector, .f = ~ str_detect(string = .x, pattern = .y))) %>%
  select(-revision_levels_vector) %>%
  mutate(revision_level = map(.x = revision_level, .f = ~ any(.x))) %>%
  unnest() %>%
  mutate(object = if_else(revision_level == TRUE, paste("revision", object, sep = "_"), object)) %>%
    group_by(object) %>%
  nest() %>%
  mutate(object_levels_side_df = data) %>%
  select(-data) %>%
  mutate(tech_statement = map2(.x = object, .y = object_levels_side_df, .f = ~ op_note_technique_statement(object = .x, levels_side_df = .y))) %>%
  select(object, tech_statement) %>%
  unnest() %>%
  distinct()



revision_decompression_test_df$level

str_detect()


test_op <- op_note_procedure_paragraphs_function(objects_added_df = lumbar_test_df, revision_decompression_vector = c("L3"))

test_op

```


```{r}
test_2_df <- lumbar_test_df %>%
  filter(approach == "posterior") %>%
  mutate(procedure_category = op_note_procedure_category_function(object = object)) %>%
  select(level, vertebral_number, procedure_category, object, side) %>%
  mutate(procedures_combine = op_note_number_of_paragraphs_for_procedure_category(procedure_cat = procedure_category)) %>%
  group_by(procedure_category, procedures_combine, object) %>%
  nest() %>%
  ungroup() %>%
  group_by(procedure_category, procedures_combine) %>%
  nest() %>%
  mutate(nested_data = map(.x = data, .f = ~ unnest(.x))) %>%
  select(-data)

test_2_df$nested_data[[5]]

test_procedures_op_full_df <- test_2_df %>%
    mutate(procedure_statement = pmap(list(..1 = procedure_category,
                                           ..2 = nested_data, 
                                           ..3 = procedures_combine),
                                    .f = ~create_full_paragraph_statement_function(procedure_paragraph_intro = ..1,
                                                                                   df_with_levels_object_nested = ..2, 
                                                                                   paragraphs_combined_or_distinct = ..3))) %>%
  select(procedure_category, procedures_combine, procedure_statement) %>%
  unnest()



test_2_df %>%
  unnest() %>%
  filter(procedures_combine == "combine") %>%
  select()

combined_proc_summary_df <- lumbar_test_df %>%
  filter(approach == "posterior") %>%
  mutate(procedure_category = op_note_procedure_category_function(object = object)) %>%
  select(level, vertebral_number, procedure_category, object, side) %>%
  mutate(procedures_combine = op_note_number_of_paragraphs_for_procedure_category(procedure_cat = procedure_category)) %>%
  filter(procedures_combine == "combine") %>%
    select(procedure_category, level, side) %>%
  group_by(procedure_category) %>%
  nest() %>%
  # ungroup() %>%
  # mutate(count = row_number()) %>%
  mutate(statement = glue("{str_to_title(procedure_category)} at {glue_collapse(data[[row_number()]]$level, sep = ', ', last = ' and ')}")) %>%
  ungroup() %>%
  mutate(statement = as.character(glue("{row_number()}. {statement}"))) 

distinct_proc_summary_df <- lumbar_test_df %>%
  filter(approach == "posterior") %>%
  mutate(procedure_category = op_note_procedure_category_function(object = object)) %>%
  select(level, vertebral_number, procedure_category, object, side) %>%
  mutate(procedures_combine = op_note_number_of_paragraphs_for_procedure_category(procedure_cat = procedure_category)) %>%
  filter(procedures_combine == "distinct") %>%
    select(procedure_category, level, side) %>%
mutate(statement = glue("{row_number()}. {str_to_title(procedure_category)} at {level}")) 


distinct_proc_summary_df

lumbar_test_df %>%
  filter(approach == "posterior") %>%
  mutate(procedure_category = op_note_procedure_category_function(object = object)) %>%
  select(level, vertebral_number, procedure_category, object, side) %>%
  mutate(procedures_combine = op_note_number_of_paragraphs_for_procedure_category(procedure_cat = procedure_category))


combined_proc_summary_df

lumbar_test_df


glue_collapse(x = test_procedures_op_full_df$procedure_statement, sep = "\n\n")

open_canal_df

```



```{r}

```



```{r}
t <- all_implants_constructed_df %>%
  filter(approach == "posterior") %>%
  mutate(procedure_category = op_note_procedure_category_function(object = object)) %>%
  select(level, vertebral_number, procedure_category, object, side) %>%
  nest_by(procedure_category, side)

t %>%
  filter(procedure_category == "decompression") %>%
  filter(side == "left") %>%
  unnest()


```

